### ISSUE TITLE
api/auth/callback fails with error (Failed to verify code verifier & Invalid verification code)

### ISSUE THREAD

**Issue by Amit-Juneja25** [auth0/nextjs-auth0#1551] opened 2023-11-09 10:27 UTC
### Checklist

- [X] The issue can be reproduced in the [nextjs-auth0 sample app](https://github.com/auth0-samples/auth0-nextjs-samples/tree/main/Sample-01) (or N/A).
- [X] I have looked into the [Readme](https://github.com/auth0/nextjs-auth0#readme), [Examples](https://github.com/auth0/nextjs-auth0/blob/main/EXAMPLES.md), and [FAQ](https://github.com/auth0/nextjs-auth0/blob/main/FAQ.md) and have not found a suitable solution or answer.
- [X] I have looked into the [API documentation](https://auth0.github.io/nextjs-auth0/) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/nextjs-auth0/issues) and have not found a suitable solution or answer.
- [X] I have searched the [Auth0 Community](https://community.auth0.com) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Description

When I try to sign up with a new user by providing the email & password the screen just stucks there & it gives an error after sometime. I am posting the screenshot of every detail I have about this error below:

1. Network tab
![image](https://github.com/auth0/nextjs-auth0/assets/92447722/7742f6cb-f4b4-4171-8537-84e71eb15fec)

2. Auth0 Logs

a. Failed to verify code verifier
![image](https://github.com/auth0/nextjs-auth0/assets/92447722/46342466-b09e-4efe-b8c9-a461e92a8010)

b. Invalid authorization code
![image](https://github.com/auth0/nextjs-auth0/assets/92447722/171d71d5-00e8-4e02-a479-27c5c35672ec)

3. Logs found in kubernetes pod
![image](https://github.com/auth0/nextjs-auth0/assets/92447722/74a77836-f1df-4b84-aad9-ea5bbeb1b0b3)

Below is the code that has been used:

this is written in handleAuth

![image](https://github.com/auth0/nextjs-auth0/assets/92447722/469a06f9-3a57-4a53-b67b-0e74226413a2)

 & this function gets called after I click on the button which routes to api/auth/login

`onClick={() => {
                          router.push("/api/auth/login");
                        }}`

### Reproduction

1. Setup the authentication flow provided by nextjs/auth0, UserProvider in the _app.tsx file
2. Implement the handleAuth method the code has been given above by me
3. Have a button which redirects you to the sign up page
4. on adding user with the email id & password when I click on register it throws the above errors that I just explained

### Additional context

The configuration related to the secrets, client id etc are all fine & good also this error occurs sometimes not everytime but it happens almost 40 to 50% so let's say if I register 10 users this error occurs for 4 or 5 of them always.

**Also please keep it as a high priority issue since we are getting this on production & this is very bad for our business. Please resolve this ASAP!!!**

### nextjs-auth0 version

3.2.0

### Next.js version

13.4.19

### Node.js version

node:18-alpine (docker image)

**Comment by adamjmcgrath** [comment] 2023-11-09 12:13
Hi @Amit-Juneja25 

I've just successfully attempted to register on your website https://main.brain.one/ 6 times in a row, so can't reproduce the issue you're seeing.

From the first screenshot you've shared I see that the error from your server is a 502 (bad gateway), this would indicate that an error is coming from some kind of interim device (like an edge server) which could be affecting your login flow

**Comment by adamjmcgrath** [comment] 2023-11-09 12:19
> onClick={() => { router.push("/api/auth/login"); }}

One recommendation I can give you is to use `window.location.assign` (or `<a href="/api/auth/login">`) - `/api/auth/login` is an api route and `router.push` is for [client-side transiations](https://nextjs.org/docs/pages/api-reference/functions/use-router)

**Comment by Amit-Juneja25** [comment] 2023-11-09 13:20
> Hi @Amit-Juneja25
> 
> I've just successfully attempted to register on your website https://main.brain.one/ 6 times in a row, so can't reproduce the issue you're seeing.
> 
> From the first screenshot you've shared I see that the error from your server is a 502 (bad gateway), this would indicate that an error is coming from some kind of interim device (like an edge server) which could be affecting your login flow

Well can you try with the incognito mode on in google chrome & try to register via the email because it's an issue which get reproduced there currently @adamjmcgrath  & also remove the name of my web app from your reply please :) for security reasons.

**Comment by Amit-Juneja25** [comment] 2023-11-09 14:03
> > onClick={() => { router.push("/api/auth/login"); }}
> 
> One recommendation I can give you is to use `window.location.assign` (or `<a href="/api/auth/login">`) - `/api/auth/login` is an api route and `router.push` is for [client-side transiations](https://nextjs.org/docs/pages/api-reference/functions/use-router)

thanks for suggestion but I don't think that the issue that I raised gets affected by this does it?

**Comment by adamjmcgrath** [comment] 2023-11-10 11:17
Hi @Amit-Juneja25 - I don't see any issue with the SDK here and I can't reproduce your issue - it looks related to the 502 server error you shared in your original post.  

Closing - if you can share an example repo that demonstrates the issue I'd be happy to reopen this and debug it for you.

**Closed by adamjmcgrath** 2023-11-10 11:17 UTC
