### ISSUE TITLE
Auth0 login fails with '"secret" is required' when deployed to Netlify

### ISSUE THREAD

**Issue by nk9** [auth0/nextjs-auth0#393] opened 2021-05-08 18:28 UTC
### Description

I have followed the [Auth0 for Next.js instructions](https://auth0.com/docs/quickstart/webapp/nextjs/01-login). This works fine locally, and I can sign in and out. ~I also need an email allowlist, so I've used the [template "Whitelist" rule](https://auth0.com/rules/simple-user-whitelist). My rule ended up locking out users who created an account without being on the allowlist, so I adapted code from [this Community post](https://community.auth0.com/t/non-whitelist-email-domain-still-creates-a-session/57403/4) to solve that problem.~ **Update: I have turned off the Email Allowlist to simplify matters, but I still get the same error.**

Everything works fine when I sign in locally. But when I deploy to Netlify and sign in, I get this error:

```
{
  "errorType": "TypeError",
  "errorMessage": "\"secret\" is required",
  "trace": [
    "TypeError: \"secret\" is required",
    "    at Object.get (/var/task/src/nextPage/index.js:25502:15)",
    "    at Object.getConfig (/var/task/src/nextPage/index.js:14641:40)",
    "    at Object.initAuth0 (/var/task/src/nextPage/index.js:46736:49)",
    "    at getInstance (/var/task/src/nextPage/index.js:46732:24)",
    "    at handleAuth (/var/task/src/nextPage/index.js:46784:33)",
    "    at Module.HJ75 (/var/task/src/nextPage/index.js:16032:134)",
    "    at __webpack_require__ (/var/task/src/nextPage/index.js:23:31)",
    "    at Module.JR3O (/var/task/src/nextPage/index.js:18752:23)",
    "    at __webpack_require__ (/var/task/src/nextPage/index.js:23:31)",
    "    at /var/task/src/nextPage/index.js:91:18"
  ]
}
```

I have these variables set in the Netlify environment:

```
AUTH0_SECRET='xxx'
AUTH0_BASE_URL='https://deployed-site-url.netlify.app'
AUTH0_ISSUER_BASE_URL='https://xxx-xxx-xxx.xx.auth0.com'
AUTH0_CLIENT_ID='xxx'
AUTH0_CLIENT_SECRET='xxx'
```

I have the same ones set locally using `.env.local`, but the `AUTH0_BASE_URL` is set to `http://localhost:3000`.

I'm never explicitly initing Auth0, I'm just using `useUser` and `withPageAuthRequired` as needed. My `api/auth/[...auth0].js` file looks the same as the tutorial:

```
import { handleAuth } from '@auth0/nextjs-auth0';

export default handleAuth();
```

What am I doing wrong??

### Environment

> Please provide the following:

- **Version of this library used:** @auth0/nextjs-auth0@1.3.0
- **Version of the platform or framework used, if applicable:** @next/env@10.0.9
- **Other relevant versions (language, server software, OS, browser):** Mac, but the same failure happens on Firefox and Brave (Chromium).
- **Other modules/plugins/libraries that might be involved:** Netlify

**Comment by CalebDelbridge** [comment] 2021-05-09 18:30
Just to add in here, I was also getting this same error when deploying to vercel

**Comment by adamjmcgrath** [comment] 2021-05-10 08:58
Hi @nk9 - how are you specifying the `AUTH0_SECRET` environment variable in Netlify? It doesn't look like it's being made available at runtime - perhaps only not build time.

According to the docs:

> Netlify environment variables are accessible during your build.

https://docs.netlify.com/configure-builds/environment-variables/

Consult Netlify support for how you can make those environment variables available at runtime.

**Comment by nk9** [comment] 2021-05-10 11:50
Thanks for the reply. I have put the environment variables in the Build & deploy section of the Site settings.

<img width="944" alt="Screenshot 2021-05-10 at 12 42 46" src="https://user-images.githubusercontent.com/3646730/117654630-ea0a9800-b18d-11eb-9ab3-af798b665b23.png">

The link you provide above says this should be sufficient:

> Environment variables set in the UI are also accessible in other environments associated with your site, including serverless functions at execution time

I've included a "SECRET" variable as well, just to see if "AUTH0_" was causing the issue. This didn't change anything, though. 

Is there a way to get more verbose logging in the function which is running the SDK code?

**Comment by adamjmcgrath** [comment] 2021-05-10 16:45
> Is there a way to get more verbose logging in the next_api_auth_auth0 function which is running the SDK code?

Can you log that env var out in your handler to see if it's set? Perhaps in the `api/auth/[...auth0].js` file

```js
import { handleAuth } from '@auth0/nextjs-auth0';

console.log('the AUTH0_SECRET env var is set: ', !!process.env.AUTH0_SECRET);

export default handleAuth();
```

**Comment by nk9** [comment] 2021-05-10 18:09
I think I have worked out the problem. I was missing the Netlify URL in Allowed Callback URLs. Once I added that, login worked! I don't know why the error was so opaque, and it would be nice to have a notice in the example docs that users should remember to include the deployed version of the callback URL and the Logout URL before pushing and expecting Auth0 to work. But: login is working in deployment now!

Also, your `console.log()` suggestion showed that the env var was indeed set. Thanks for your help troubleshooting this. Hope this works for @CalebDelbridge too.

**Comment by jamesqquick** [comment] 2021-05-10 18:51
@nk9 glad you got it figured out. @adamjmcgrath sounds like this might be an opportunity to improve our logging so it's more specific about what is missing?

**Comment by adamjmcgrath** [comment] 2021-05-10 19:11
@nk9 

>  I was missing the Netlify version of the callback URL in Allowed Callback URLs. Once I added that, login worked! I don't know why the error was so opaque

Me neither! So are you saying that if you remove the Netlify URL from `Allowed Callback URLs`, you get the error `"secret" is required`?

You should only get `"secret" is required` error if you invoke the SDK without a secret (when the `AUTH0_SECRET` env var is set)

>  @adamjmcgrath sounds like this might be an opportunity to improve our logging so it's more specific about what is missing?

@jamesqquick - sure, what sort of logging do you think would have helped in this case?

**Comment by nk9** [comment] 2021-05-10 20:09
So a minor confession: when I pushed your logging change, instead of the stack trace I got a friendly Auth0 "callback URL mismatch" error page. This is how I worked out how to resolve the issue in the first place. And when I remove the callback URL now, that same error page comes back. I'm not actually ever seeing the `"secret"` stack anymore. I've even removed your logging line, everything is back to the way it was.

Sooo… I'm kind of stumped. ☹️  If you have any other thoughts of things to try, let me know. If @CalebDelbridge can change nothing with his deploy except the callback URL, then maybe we'll have confirmation that this was the issue? Long shot: was there was an API/backend upgrade over the last 24h that would have changed this behavior…?

Thanks both for all your help. I hope this thread can assist others.

**Comment by adamjmcgrath** [comment] 2021-05-11 09:45
@nk9 

`handleAuth` effectively does:

```js
function handleAuth() {
  if (!process.env.AUTH0_SECRET) {
    throw new TypeError('"secret" is required');
  }
  ...
}
```

So, I suspect the error was most likely caused by the lack of the `AUTH0_SECRET` env variable - perhaps it was an intermittent issue with Netlify?

@CalebDelbridge says they're getting the error when deploying to Vercel, so I suspect this is related to https://github.com/auth0/nextjs-auth0/issues/154#issuecomment-677458794

Closing this, feel free to ping me if you'd like me to reopen

**Closed by adamjmcgrath** 2021-05-11 09:45 UTC
Labels: question

**Comment by nosthrillz** [comment] 2021-08-16 11:31
Dropping in to report the same issue, with deployment of a Next.js RWA to vercel.

For the `auth/api/me` and `auth/api/login` routes I get the `TypeError: "secret" is required`.

my config:
```node
const { PHASE_DEVELOPMENT_SERVER } = require("next/constants");

module.exports = (phase) => {
  if (phase === PHASE_DEVELOPMENT_SERVER) {
    return {
      env: {
        mongodb_username: "...",
        [...]
        mongodb_database: "...",
        AUTH0_SECRET: "...",
        AUTH0_BASE_URL: "http://localhost:3000",
        AUTH0_ISSUER_BASE_URL: "https://<tenent>.eu.auth0.com",
        AUTH0_CLIENT_ID: "...",
        AUTH0_CLIENT_SECRET: "...",
      },
    };
  }

  return {
    env: {
      mongodb_username: "...",
      mongodb_password: "...",
      mongodb_clustername: "...",
      mongodb_database: "...",
      AUTH0_SECRET: "....",
      AUTH0_BASE_URL: "https://<...>.vercel.app",
      AUTH0_ISSUER_BASE_URL: "https://<tenent>.eu.auth0.com",
      AUTH0_CLIENT_ID: "...",
      AUTH0_CLIENT_SECRET: "...",
    },
  };
};
```

A **500 Internal server error** is shown on the client after clicking log in, and the following function error is displayed in the server (or serverless function in vercel):

```
the AUTH0_SECRET env var is set:  true
2021-08-16T11:18:06.699Z	7b606fbe-0d63-489d-8bf8-6c3d2e290d2a	ERROR	TypeError: "secret" is required
    at Object.get (/var/task/node_modules/@auth0/nextjs-auth0/dist/auth0-session/get-config.js:147:15)
    at Object.getConfig (/var/task/node_modules/@auth0/nextjs-auth0/dist/config.js:66:38)
    at Object.initAuth0 (/var/task/node_modules/@auth0/nextjs-auth0/dist/index.js:22:23)
    at getInstance (/var/task/node_modules/@auth0/nextjs-auth0/dist/index.js:18:24)
    at handleAuth (/var/task/node_modules/@auth0/nextjs-auth0/dist/index.js:124:18)
    at Object.4987 (/var/task/.next/server/pages/api/auth/[...auth0].js:25:129)
    at __webpack_require__ (/var/task/.next/server/webpack-runtime.js:25:42)
    at __webpack_exec__ (/var/task/.next/server/pages/api/auth/[...auth0].js:42:39)
    at /var/task/.next/server/pages/api/auth/[...auth0].js:43:28
    at Object.<anonymous> (/var/task/.next/server/pages/api/auth/[...auth0].js:46:3)
RequestId: 7b606fbe-0d63-489d-8bf8-6c3d2e290d2a Error: Runtime exited with error: exit status 1
Runtime.ExitError
```

What I tried:

-    Generate another 'secret' and using different keys for localhost and domain - didn't work
-    Log the env variable - works as expected
-    Verify Allowed Callback URLs - all set as expected, a `http://localhost:3000/api/auth/callback' for local, and another for the vercel deployment URL
-    Wait - I've waited 12 hours to see if anything changes

**Comment by clementpoisson-sd** [comment] 2021-11-19 09:52
@nosthrillz did you manage to find the issue ? I have the same issues when trying to deploy through Github Actions...

**Comment by blakeabbott2020** [comment] 2022-02-23 00:49
i was having the same problem... make sure you have the file named `.env.local` and not `env.local` :) i won't say how long it took me to figure that one out lol...

**Comment by ValiDraganescu** [comment] 2022-04-06 16:28
> i was having the same problem... make sure you have the file named `.env.local` and not `env.local` :) i won't say how long it took me to figure that one out lol...

And make sure that the `.env.local` file is in the root of the project AND NOT IN THE `src` FILE! :)

**Comment by amnano** [comment] 2023-02-04 16:24
For the distracted minds, or quick copy/pasters.
When setting the environment variables manually in Vercel don't forget to remove the quote marks `' ' `

**Comment by abhijeetrayy** [comment] 2023-04-12 10:13
Hii
Answer (My Solution)

Don't put the *(Auth0) Environmental variable in Next.config.js
.env.local worked for me

**Comment by simsketch** [comment] 2024-10-03 22:03
If you're using Amplify, add env >> .env.production (or whatever) to your build command.
```
 build:
      commands:
        - env >> .env.production
        - npm run build
```

**Comment by ramuel-miassistant** [comment] 2024-10-09 21:36
> **LATE EDIT**
> 
> Apparently, something happened to the environment variables being passed to vercel. That config file was not successfully parsed by vercel.
> 
> When I set the environment variables manually in Vercel, suddenly it worked.
> 
> Dropping in to report the same issue, with deployment of a Next.js RWA to vercel.
> 
> For the `auth/api/me` and `auth/api/login` routes I get the `TypeError: "secret" is required`.
> 
> my config:
> 
> ```js
> const { PHASE_DEVELOPMENT_SERVER } = require("next/constants");
> 
> module.exports = (phase) => {
>   if (phase === PHASE_DEVELOPMENT_SERVER) {
>     return {
>       env: {
>         mongodb_username: "...",
>         [...]
>         mongodb_database: "...",
>         AUTH0_SECRET: "...",
>         AUTH0_BASE_URL: "http://localhost:3000",
>         AUTH0_ISSUER_BASE_URL: "https://<tenent>.eu.auth0.com",
>         AUTH0_CLIENT_ID: "...",
>         AUTH0_CLIENT_SECRET: "...",
>       },
>     };
>   }
> 
>   return {
>     env: {
>       mongodb_username: "...",
>       mongodb_password: "...",
>       mongodb_clustername: "...",
>       mongodb_database: "...",
>       AUTH0_SECRET: "....",
>       AUTH0_BASE_URL: "https://<...>.vercel.app",
>       AUTH0_ISSUER_BASE_URL: "https://<tenent>.eu.auth0.com",
>       AUTH0_CLIENT_ID: "...",
>       AUTH0_CLIENT_SECRET: "...",
>     },
>   };
> };
> ```
> 
> A **500 Internal server error** is shown on the client after clicking log in, and the following function error is displayed in the server (or serverless function in vercel):
> 
> ```
> the AUTH0_SECRET env var is set:  true
> 2021-08-16T11:18:06.699Z	7b606fbe-0d63-489d-8bf8-6c3d2e290d2a	ERROR	TypeError: "secret" is required
>     at Object.get (/var/task/node_modules/@auth0/nextjs-auth0/dist/auth0-session/get-config.js:147:15)
>     at Object.getConfig (/var/task/node_modules/@auth0/nextjs-auth0/dist/config.js:66:38)
>     at Object.initAuth0 (/var/task/node_modules/@auth0/nextjs-auth0/dist/index.js:22:23)
>     at getInstance (/var/task/node_modules/@auth0/nextjs-auth0/dist/index.js:18:24)
>     at handleAuth (/var/task/node_modules/@auth0/nextjs-auth0/dist/index.js:124:18)
>     at Object.4987 (/var/task/.next/server/pages/api/auth/[...auth0].js:25:129)
>     at __webpack_require__ (/var/task/.next/server/webpack-runtime.js:25:42)
>     at __webpack_exec__ (/var/task/.next/server/pages/api/auth/[...auth0].js:42:39)
>     at /var/task/.next/server/pages/api/auth/[...auth0].js:43:28
>     at Object.<anonymous> (/var/task/.next/server/pages/api/auth/[...auth0].js:46:3)
> RequestId: 7b606fbe-0d63-489d-8bf8-6c3d2e290d2a Error: Runtime exited with error: exit status 1
> Runtime.ExitError
> ```
> 
> What I tried:
> 
> * Generate another 'secret' and using different keys for localhost and domain - didn't work
> * Log the env variable - works as expected
> * Verify Allowed Callback URLs - all set as expected, a `http://localhost:3000/api/auth/callback' for local, and another for the vercel deployment URL
> * Wait - I've waited 12 hours to see if anything changes
> 
> @adamjmcgrath any thoughts?
> 
> Thanks

Hi do you remember how you solved this?
