### ISSUE TITLE
How to differentiate between `Login` or new `Registration`?

### ISSUE THREAD

**Issue by Aravin** [auth0/nextjs-auth0#670] opened 2022-05-22 11:24 UTC
I have to store the details in my database post-registration.

I can see `hooks` from the Auth0 dashboard but is there a way to consume it programmatically?

**Comment by adamjmcgrath** [comment] 2022-05-23 16:03
This looks like a duplicate of #671

**Closed by adamjmcgrath** 2022-05-23 16:03 UTC
