### ISSUE TITLE
Auth0 api handler get stalled at Amplify and Next.js 12

### ISSUE THREAD

**Issue by CauanCabral** [auth0/nextjs-auth0#1463] opened 2023-09-28 14:10 UTC
### Checklist

- [X] The issue can be reproduced in the [nextjs-auth0 sample app](https://github.com/auth0-samples/auth0-nextjs-samples/tree/main/Sample-01) (or N/A).
- [X] I have looked into the [Readme](https://github.com/auth0/nextjs-auth0#readme), [Examples](https://github.com/auth0/nextjs-auth0/blob/main/EXAMPLES.md), and [FAQ](https://github.com/auth0/nextjs-auth0/blob/main/FAQ.md) and have not found a suitable solution or answer.
- [X] I have looked into the [API documentation](https://auth0.github.io/nextjs-auth0/) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/nextjs-auth0/issues) and have not found a suitable solution or answer.
- [X] I have searched the [Auth0 Community](https://community.auth0.com) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Description

I found a topic at [Community with the same problem](https://community.auth0.com/t/auth0-nextjs-stuck-on-loading/103352), but no issue was created, so I am doing it.

I followed the [Basic Sample](https://github.com/auth0/nextjs-auth0/blob/v2.7.0/EXAMPLES.md#basic-setup):

File `pages/api/auth/[...auth0].ts` with content:

```ts
import { handleAuth } from '@auth0/nextjs-auth0';

export default handleAuth();
```

But when I load any route:

 - /api/auth/me
 - /api/auth/login
 - /api/auth/logout

The response was:

![image](https://github.com/auth0-samples/auth0-nextjs-samples/assets/83092/a1d03f3d-8c8f-422c-afa4-ed0ce8221757)

The logged warning at Cloudwatch was:

```
WARN	API resolved without sending a response for /api/auth/me, this may result in stalled requests.
```

### Reproduction

1. Configure Next.js App in Amplify
2. Add nextjs-auth0 2.7.0
3. Add Environment variables
4. Build
5. Access any auth endpoint

### Additional context

My stack is:

 - Node.js 18 at build
 - Node.js 14 at lambda@edge (tried Node.js 18 too)
 - Next.js 12.3.4 (tried 12.1 initially)
 - Auth0-Next.js 2.7.0
 - Amplify in Web Dynamic mode

I have one other project running with almost the same stack and working, the only difference is the `nextjs-auth0` version: `1.9.1`

### nextjs-auth0 version

2.7.0

### Next.js version

12.3.4

### Node.js version

14

**Comment by CauanCabral** [comment] 2023-09-28 18:20
Downgraded the `nextjs-auth0` to `1.9.1` and the same App/Env which doesn't work with `2.7.0` is working.

Version 2.7.0 isn't supposed to work with Next.js 12 and Node.js 12+?

**Comment by adamjmcgrath** [comment] 2023-10-02 09:26
Hi @CauanCabral - thanks for raising this

I don't have an AWS account to test this on and also I'm not sure what "Configure Next.js App in Amplify" would entail.

The following endpoints do not return JSON by design:

- /api/auth/login
- /api/auth/logout
- /api/auth/me (when unauthenticated)

So this may be why you're getting "The Lambda function returned invalid JSON"

> WARN API resolved without sending a response for /api/auth/me, this may result in stalled requests.

Also `/api/auth/me` returns "204 No Content" by design when the user is not authenticated - so this might explain this warning

**Comment by CauanCabral** [comment] 2023-10-02 17:58
Hi @adamjmcgrath , thank you for your response.

> I don't have an AWS account to test this on and also I'm not sure what "Configure Next.js App in Amplify" would entail.

It's not really complex or important I think - it's just like creating a Project on Vercel or Netlify, but at AWS.
Consists of linking a Next.js source code project (from Github, Gitlab, or Bitbucket) with the service.

> The following endpoints do not return JSON by design:

I see, but this kind of error on Cloudfront / Lambda@EDGE is more related to the code being async without waiting for its execution or not returning the Promise.

Example (consider a file `pages/api/sample.js`:

```
export function handler(req, res) {
  fetch('SOME_API').then(apiRes => return apiRes.json()).then(body => res.json(body).send());
}
```

That code will generate a stalled response because the handler function doesn't wait for `fetch` complete.

Also, the same code is working with version `1.9.1` of the lib.

Theres any relevant change from `1.9.1` to `2.7.0` considering the Api handler? I reviewed the lib source code but I can't find any change to justify that break.

**Comment by adamjmcgrath** [comment] 2023-10-03 13:26
> Theres any relevant change from 1.9.1 to 2.7.0 considering the Api handler? I reviewed the lib source code but I can't find any change to justify that break.

Me neither, there's no case where code is not waiting for async code before returning a response (otherwise the response would fail on the dev server too)

Could you try with the latest version of the SDK?

Also could you experiment with different return values for the auth handler? eg

```js
import { handleAuth } from '@auth0/nextjs-auth0';

export default handleAuth();

// or
export default function(req, res) {
  return handleAuth()(req, res);
};

// or
export default async function(req, res) {
  return await (handleAuth())(req, res);
};


// or
export default async function(req, res) {
  await (handleAuth())(req, res);
  return res;
};

// etc....
```

**Comment by CauanCabral** [comment] 2023-10-05 19:02
Thanks a lot @adamjmcgrath, but I tried every single combination with both `2.7.0` and `3.2.0` without success.

Only version 1.9.4 works for me.

Should be a bug in https://github.com/aws-amplify/amplify-hosting

**Comment by Bohemus307** [comment] 2023-10-06 11:54
Currently using the sdk with amplify at latest without issue. One thing to check for is if your app is setup for nextjs set. https://docs.aws.amazon.com/amplify/latest/userguide/deploy-nextjs-app.html

**Comment by CauanCabral** [comment] 2023-10-06 12:51
Hi @Bohemus307 , thank you for your time.

Can you share if you use Amplify in Web Compute (new mode) or Classic/Web Dynamic?

In my case, the App uses Classic/Web Dynamic, and the SSR mode is enabled (the package works fine with version 1.9.4) .

**Comment by Bohemus307** [comment] 2023-10-06 13:20
@CauanCabral  I am on a web compute. Did u go with a older version of Nextjs? Also, are u passing `Amplify.configure({ ...awsExports, ssr: true });` in all pages using the api?

**Comment by CauanCabral** [comment] 2023-10-06 14:14
>  I am on a web compute.

I suspected it was an issue with Amplify Classic.

> Did u go with a older version of Nextjs?

I'm using version Next.js 12.3.4. I did not upgrade the Amplify because I had many issues when I tested it early in this year.

But I think it's time to try again.

> Amplify.configure({ ...awsExports, ssr: true }); in all pages using the API?

I didn't get it. What do you mean by `all pages using the API`?

Because the API is always a kind of SSR (run in its own Lambda) and I call it from the client side (so for the page consumer, doesn't matter if it is SSG, SSR, or ISR).

**Comment by Bohemus307** [comment] 2023-10-06 14:24
my apologies while extremely vague the term API is how AWS refers to the API package inside Amplify. So that includes server-side functions and API usage inside components as well.  They have documentation surrounding this but it's not always easy to locate. https://docs.amplify.aws/lib/ssr/q/platform/js/

**Comment by CauanCabral** [comment] 2023-10-06 16:36
I see @Bohemus307 , I know I saw that signature somewhere before - thank you for your patience.

In fact, I don't use the Amplify SDK (although I have some Next.js running in Amplify 2020 using SSR, SSG, and API), but I will give it a try.

But again, I suspect the main difference here is the use of WEB_COMPUTE instead of WEB_DYNAMIC.

**Comment by adamjmcgrath** [comment] 2023-10-17 08:15
I don't think there's any action for the SDK to take here, closing. Feel free to ping me if you want to reopen

**Closed by adamjmcgrath** 2023-10-17 08:15 UTC
Labels: question
