### ISSUE TITLE
@auth0/nextjs-auth0 calling me.js prior to login

### ISSUE THREAD

**Issue by bc2012** [auth0/nextjs-auth0#760] opened 2022-07-14 02:34 UTC
### Description
Quite a while ago I asked this question https://community.auth0.com/t/auth0-nextjs-auth0-calling-me-prior-to-login/63244 and the advice was to "to raise it as a GitHub issue in the repo so we can talk about it directly with the repo maintainers. ". I got distracted with other stuff but I am trying to resurrect this project and I still have the same issue.

### Reproduction
Please also see https://community.auth0.com/t/auth0-nextjs-auth0-calling-me-prior-to-login/63244 fro code examples.

When the user clicks login or signup on my app's website there is a 6-7 sec delay before the Auth0 login/signup box appears.
The website is either calling login.js or signup.js depending on which the user choose.
As well as the 6-7sec delay, the problem that I am also having is that my call to login.js or signup.js is also automatically calling /api/auth/me. Given that the user has not logged in yet this call to /api/auth/me returns 401 Unauthorised - which is correct but it seems to me that this call shouldn’t be being made in the first place. It may be that my setup is not correct?

### Code for me.js
import auth0 from '../../utils/auth0'

export default async function me(req, res) {
  try {
    await auth0.handleProfile(req, res)
  } catch (error) {
    console.error(error)
    res.status(error.status || 500).end(error.message)
  }
}

### Environment
auth0@2.42.0
@auth0/nextjs-auth0@1.9.1
next@12.2.1

**Comment by adamjmcgrath** [comment] 2022-07-14 10:24
Hi @bc2012 - thanks for raising this

> When the user clicks login or signup on my app's website there is a 6-7 sec delay before the Auth0 login/signup box appears.

I can't reproduce this on the example app. If you cold share a har file that demonstrates this issue I'd be happy to take a look at it

> the problem that I am also having is that my call to login.js or signup.js is also automatically calling /api/auth/me

By "call to login.js" do you mean making a request to `/api/auth/login`? All this page does is serve a 302, it shouldn't make your browser make a request to `/api/auth/me`

**Comment by bc2012** [comment] 2022-07-15 05:53
Hi @adamjmcgrath - thanks for taking a look.

I have added har files for Firefox Developer and Chrome.

On the website:
When the user clicks ‘Signup’: <a href="https://app.myapp.com/Join" id="homeJoin">Signup</a>
This calls Join.js which in turn calls signup.js

When the user clicks ‘Login’: <a href="https://app.myapp.com/Login" id="homeLogin">Login</a>
This calls Login.js which in turn calls login.js

I have added these files also.

[firefox-myapp.us.auth0.com_Archive [22-07-15 10-51-44].har.txt](https://github.com/auth0/nextjs-auth0/files/9118161/firefox-myapp.us.auth0.com_Archive.22-07-15.10-51-44.har.txt)
![firefox](https://user-images.githubusercontent.com/2817945/179158905-0d2b7b33-9125-4426-9c97-2c78bd3e4aff.jpg)
[chrome-myapp.us.auth0.com.har.txt](https://github.com/auth0/nextjs-auth0/files/9118165/chrome-myapp.us.auth0.com.har.txt)
![chrome](https://user-images.githubusercontent.com/2817945/179159028-dbf0ce22-5dc1-40c8-991b-b9b745baf278.jpeg)
[Join.js.txt](https://github.com/auth0/nextjs-auth0/files/9118199/Join.js.txt)
[Login.js.txt](https://github.com/auth0/nextjs-auth0/files/9118200/Login.js.txt)
[lowercase_login.js.txt](https://github.com/auth0/nextjs-auth0/files/9118201/lowercase_login.js.txt)
[signup.js.txt](https://github.com/auth0/nextjs-auth0/files/9118202/signup.js.txt)

**Comment by bc2012** [comment] 2022-07-15 05:55
Here is me.js too!
[me.js.txt](https://github.com/auth0/nextjs-auth0/files/9118216/me.js.txt)

**Comment by adamjmcgrath** [comment] 2022-07-25 11:27
Closing, feel free to ping me if you want to reopen

**Closed by adamjmcgrath** 2022-07-25 11:27 UTC
Labels: question
