### ISSUE TITLE
Users unable to login with Auth0 if MSW is running

### ISSUE THREAD

**Issue by ollie-ki** [auth0/nextjs-auth0#606] opened 2022-03-02 11:36 UTC
### Description

> Provide a clear and concise description of the issue, including what you expected to happen.

**Issue:** When [MSW](https://github.com/mswjs/msw) is running on next.js, users are _unable_ to login to the application locally.
**Expected:** When [MSW](https://github.com/mswjs/msw) is running on next.js, users _should_ be able to login to the application locally.

### Reproduction

- Setup a [next.js auth0 repo](https://github.com/auth0-samples/auth0-nextjs-samples/tree/main/Sample-01)
- Add the setup from the [next.js msw repo](https://github.com/vercel/next.js/tree/canary/examples/with-msw) 
- When a user logs in, they get `Cannot read properties of undefined (reading &#39;content-encoding&#39;)` shown on the page.

```bash
wait  - compiling /api/auth/[...auth0]...
event - compiled client and server successfully in 57 ms (214 modules)
error - unhandledRejection: TypeError: Cannot read properties of undefined (reading 'content-encoding')
HandlerError [RequestError]: Cannot read properties of undefined (reading &#39;content-encoding&#39;)
    at new HandlerError (xxx/app/node_modules/@auth0/nextjs-auth0/dist/utils/errors.js:53:28)
    at Object.<anonymous> (/xxx/app/node_modules/@auth0/nextjs-auth0/dist/handlers/login.js:35:31)
    at step (xxx/app/node_modules/@auth0/nextjs-auth0/node_modules/tslib/tslib.js:143:27)
    at Object.throw (xxx/app/node_modules/@auth0/nextjs-auth0/node_modules/tslib/tslib.js:124:57)
    at rejected (xxx/app/node_modules/@auth0/nextjs-auth0/node_modules/tslib/tslib.js:115:69)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  code: 'ERR_GOT_REQUEST_ERROR'
}
error - unhandledRejection: TypeError: Cannot read properties of undefined (reading 'content-encoding')
```

The issue is _immediately_ remedied by turning off MSW. Even if MSW doesn't have any handlers, [nextjs-auth0](https://github.com/auth0/nextjs-auth0) still seems to break.

It looks like it's the callback request(?)
<img width="945" alt="Screenshot 2022-03-02 at 11 51 55" src="https://user-images.githubusercontent.com/78483427/156356761-7df9b08b-856b-4c0e-9a0c-94774a9f6588.png">

```js
const { setupWorker } = require('msw');
const { setupServer } = require('msw/node');

if (typeof window === 'undefined') {
  const server = setupServer();
  server.listen({ onUnhandledRequest: 'bypass' });
} else {
  const worker = setupWorker();
  worker.start({ onUnhandledRequest: 'bypass' });
}
```

### Environment

> Please provide the following:

- **Version of this library used:** `1.7.0`
- **Version of the platform or framework used, if applicable:** `next: 12.1.0`
- **Other relevant versions (language, server software, OS, browser):** `Mac OS` `Chrome` `Firefox`
- **Other modules/plugins/libraries that might be involved:** `MSW`

**Comment by ollie-ki** [comment] 2022-03-03 11:01
Hi there!
-  `node_modules/@mswjs/interceptors: 0.13.4`
-  `node version :16.14.0`

Thanks, Ollie

**Comment by adamjmcgrath** [comment] 2022-03-03 11:15
Yep it looks like https://github.com/mswjs/interceptors/issues/212

Can you upgrade `@mswjs/interceptors` to `0.13.6` and let me know if you still experience the issue?

**Comment by ollie-ki** [comment] 2022-03-03 11:58
I've updated everything to `0.13.6` and whilst it's not erroring any more (progress!) requests like logout never resolve, they just infinitely wait :/

**Comment by adamjmcgrath** [comment] 2022-03-03 13:43
I'm not sure how msw works, but I suspect this isn't an issue with the SDK.

If you can debug it some more and find an issue with the SDK I'd be happy to take a look, alternatively if you'd like me to debug it for you - can you share a running example that demonstrates the issue

**Comment by adamjmcgrath** [comment] 2022-03-07 09:32
Closing - happy to reopen if you want to share a running example that demonstrates the issue

**Closed by adamjmcgrath** 2022-03-07 09:32 UTC
Labels: question

**Comment by rickymarcon** [comment] 2022-03-19 01:01
> I've updated everything to `0.13.6` and whilst it's not erroring any more (progress!) requests like logout never resolve, they just infinitely wait :/

@ollie-ki Same here. Trying to logout hangs. 

Tried using latest packages for all dependencies, including updating `openid-client` to no avail...

Debugging shows the last event to have successfully cloned a request to `/.well-known/openid-configuration`, but then hangs after the event closes. Any ideas on what could be causing this? Underlying `got` client?

**Comment by rickymarcon** [comment] 2022-03-19 01:12
So after a bit of troubleshooting I isolated the problem to the `msw@0.38.0` release. 

Downgrading to `msw@0.36.8` works.

**Comment by Carrein** [comment] 2022-03-23 15:28
Can confirm I'm experiencing the same issue with `msw@0.39.2` with a brand new NextJS example and the associated Auth0 library. 
Related issue here: https://github.com/mswjs/msw/issues/700 
Downgrading fixes this issue.

**Comment by massimopalmieri** [comment] 2022-04-20 13:45
I'm also experiencing a similar issue, It only happens with POST requests with a body done through axios.
downgrading to msw@0.36.8 or performing that request with node-fetch instead of axios solves the issue for me

**Comment by awacode21** [comment] 2022-11-17 20:19
> > I've updated everything to `0.13.6` and whilst it's not erroring any more (progress!) requests like logout never resolve, they just infinitely wait :/
> 
> @ollie-ki Same here. Trying to logout hangs.
> 
> Tried using latest packages for all dependencies, including updating `openid-client` to no avail...
> 
> Debugging shows the last event to have successfully cloned a request to `/.well-known/openid-configuration`, but then hangs after the event closes. Any ideas on what could be causing this? Underlying `got` client?

having absolutely same problem, but downgrading MSW is not an option as we need to use latest version to not get other issues with MSW :-( anything new on this?

**Comment by kettanaito** [comment] 2022-11-18 13:41
One thing I always ask people to check is whether they're using the latest `msw` as updates of pre-1.0 packages may not be apparent to some. Can somebody please verify that this issue is still there with the following dependencies?

- `msw@latest`

You should get `msw@0.48.3` and `@mswjs/interceptors@0.17.5`.

**Comment by awacode21** [comment] 2022-11-18 14:03
@kettanaito i can confirm. i created an issue at msw github and linked a reproduction. using latest msw version 0.48.3

Issue:
https://github.com/mswjs/msw/issues/1468

Reproduction:
https://codesandbox.io/p/github/awacode21/reproduction-vue-ssr-auth0-msw-bug/msw-issue?file=%2Fpackage.json
