### ISSUE TITLE
Link to a protected page fails when using i18n routes with next 11.1.0

### ISSUE THREAD

**Issue by vitormv** [auth0/nextjs-auth0#464] opened 2021-08-16 19:32 UTC
### Describe the problem

When using the latest Next.js `v11.1.0`, and having i18n routes enabled, any `<Link />` that points to a protected page will fail. In Next.js 11.1, they removed the locale prefix from api routes, but it seems Auth0 package is still trying to redirect to a locale prefixed route.

I tried setting up "NEXT_PUBLIC_AUTH0_LOGIN="/api/auth/login"" in the `.env` file. Also tried to manually set the login route in the <UserProvider>, but the issue persists

### What was the expected behavior?

User should be redirected to `/api/auth/login` instead of `/en/api/auth/login`.

### Reproduction

I created a sample codebox where you can see the issue. Clicking on the regular `<a>` link works fine (ignore the error page on the Auth0 side). But trying to reach the same package when using a `<Link />` leads to a redirect to api route with a prefix.

https://codesandbox.io/s/peaceful-smoke-0iubu

Of course, the external Auth0 login page will show an error since there are no correct Auth0 for a real project, but just reaching the page can be considered a "success" in this case.

### Environment
```
    "@auth0/nextjs-auth0": "1.5.0",
    "next": "11.1.0",
    "react": "^16.13.1",
    "react-dom": "^16.13.1"
```

**Comment by Widcket** [comment] 2021-08-17 02:13
Hi @vitormv, thanks for raising this.
> I created a sample codebox where you can see the issue

Can you please share your reproduction app?

**Comment by vitormv** [comment] 2021-08-17 06:46
Ahh sorry, forgot to paste the link above! https://codesandbox.io/s/peaceful-smoke-0iubu

**Comment by Widcket** [comment] 2021-08-19 03:34
Hi @vitormv, I was not able to take a look yet. By the end of the week most likely.

**Comment by Widcket** [comment] 2021-08-24 01:12
@vitormv indeed, this does not happen with Next.js < 1.11.0. Thanks for providing the reproduction app.
cc @adamjmcgrath see https://github.com/vercel/next.js/pull/26629

**Comment by adamjmcgrath** [comment] 2021-08-24 15:32
Hi @vitormv - we'll have to investigate what we can do for this.

In the meantime you can workaround it by prefixing the base url to your login url, eg `NEXT_PUBLIC_AUTH0_LOGIN="$AUTH0_BASE_URL/api/auth/login"`

Just bear in mind that our solution may involve doing this, which would break your workaround.

note to self: we may have to stop using the `redirect` prop of `getServerSideProps` https://github.com/auth0/nextjs-auth0/blob/main/src/helpers/with-page-auth-required.ts#L114 - but I remember there was a different issue with using `res.writeHead(30x, ...`

**Comment by RyanClementsHax** [comment] 2021-09-19 18:07
Hello,
This is also a problem I'm running into. Thanks for all the work y'all put behind this repo btw. It is providing me a lot of value.

I took a look into this myself and while I didn't find a workaround/fix, I did notice some patterns I figured I would contribute. All of the following is reproduced in the following [reproduction app](https://github.com/RyanClementsHax/nextjs-auth0-locale-issue) (it's based on the auth0 nextjs [quickstart](https://auth0.com/docs/quickstart/webapp/nextjs) found [here](https://github.com/auth0-samples/auth0-nextjs-samples/tree/main/Sample-01)) which demonstrates the same problem @vitormv found.

The first thing I noticed was an error produced when navigating to a protected route using a `Link` tag when unauthenticated. i.e. you're on `localhost:3000`, but then click a link to a protected route (ex: `ssr`). This is also present in the reproduction example from @vitormv. I'm not exactly sure it is related, but I figured I'd mention it since I'm not sure how to interpret the error:

![image](https://user-images.githubusercontent.com/20916810/133937645-b674e406-4f77-4995-b477-94cd0fef21a7.png)

The second thing I noticed was that when the protected url was directly accessed instead of linked to via `Link` tag, the redirections worked just fine (i.e. `href="/ssr"` fails, but putting `localhost:3000/ssr` directly into the browser address bar works just fine). This seems to be a result of the different headers produced between the two actions as evidenced by the diffs below of the get server side props context object. They are from the personal project of mine where I'm localizing in spanish (`es`) and trying to link to a protected route called `/home` from a localized non authenticated page (`localhost:3000/es`). The one on the left was produced when you would link to a protected route from the `localhost:3000/es` page and the one on the right is produced from putting the protected route directly into the address bar. Only parts of the diff were included for bevity. Log out the context object in the reproduction example to see more.
![image](https://user-images.githubusercontent.com/20916810/133938003-ec668fb2-50ae-4f92-b787-7a8f0c9251e0.png)
![image](https://user-images.githubusercontent.com/20916810/133938015-ab3f8c14-1d54-441c-8224-4f79b6cefccb.png)

**Comment by RyanClementsHax** [comment] 2021-09-19 20:30
> In the meantime you can workaround it by prefixing the base url to your login url, eg `NEXT_PUBLIC_AUTH0_LOGIN="$AUTH0_BASE_URL/api/auth/login"`

I have confirmed that this workaround works in my case (thanks for posting it). I did run into a typing problem when instantiating my own instance of auth0 and figured I'd post it to save the next person some time.

The following should work, but the config type for `initAuth0` (found [here](https://github.com/auth0/nextjs-auth0/blob/d568e524ab54586b0519ce8b63d4923f5be5e942/src/auth0-session/config.ts#L7)) doesn't line up with the type used to parse the parameters which includes the login url override (found [here](https://github.com/auth0/nextjs-auth0/blob/d568e524ab54586b0519ce8b63d4923f5be5e942/src/config.ts#L378)).
```ts
// lib/auth/auth0.ts or wherever you want to put it
import { initAuth0 } from '@auth0/nextjs-auth0'

export default initAuth0({
  // ... other config
  routes: {
    login: `${process.env.AUTH0_BASE_URL}/api/auth/login`
  }
})
```
To get around this, I used a type cast like so:
```ts
// lib/auth/auth0.ts or wherever you want to put it
import {
  initAuth0,
  ConfigParameters,
} from '@auth0/nextjs-auth0'

export default initAuth0({
  // ... other config
  routes: {
    login: `${process.env.AUTH0_BASE_URL}/api/auth/login`
  }
} as ConfigParameters)
```

**Comment by adamjmcgrath** [comment] 2022-01-28 12:30
Closing this, as the workaround is the best we can offer for now. Will reassess this when considering a next major version

**Closed by adamjmcgrath** 2022-01-28 12:30 UTC
Labels: needs investigation
