### ISSUE TITLE
Issue after callback

### ISSUE THREAD

**Issue by marcNY** [auth0/nextjs-auth0#984] opened 2022-12-30 15:51 UTC
### Checklist

- [X] The issue can be reproduced in the [sample app](https://github.com/auth0-samples/auth0-nextjs-samples/tree/main/Sample-01) (or N/A).
- [X] I have looked into the [README](https://github.com/auth0/nextjs-auth0#readme) and have not found a suitable solution or answer.
- [X] I have looked into the [examples](https://github.com/auth0/nextjs-auth0/blob/main/EXAMPLES.md) and have not found a suitable solution or answer.
- [X] I have looked into the [API documentation](https://auth0.github.io/nextjs-auth0/) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/nextjs-auth0/issues) and have not found a suitable solution or answer.
- [X] I have searched the [Auth0 Community](https://community.auth0.com/c/sdks/5) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Description

I have protected my app with middlware using the code: 

// middleware.js
import { withMiddlewareAuthRequired } from "@auth0/nextjs-auth0/edge";

```
export default withMiddlewareAuthRequired();

export const config = {
  matcher: [
    /*
     * Match all request paths except for the ones starting with:
     * - api (API routes)
     * - _next/static (static files)
     * - favicon.ico (favicon file)
     */
    "/((?!404|400).*)",
  ],
};
```
I have added a rule to filter out users that are not set as active in app_metadata

My issue is that onece I get a callback, If I want to go again to localhost:3000, it directs me directly to the callback again so I am stuck.

Can you help?

### Reproduction

1. Use the sample app but set up auth0 Actions so you get an Unauthorized Error.
2. Loggin
3. You will get redirected to the callback url
4. Go back to localhost:3000
5. This will redirect you directly to the error callback url

### SDK version

2

### Next.js version

13

### Node.js version

18

**Comment by Nirajn2311** [comment] 2022-12-31 10:31
Hi, I'm also facing a similar issue. Are you denying access in the action using `api.access.deny('Access denied.')`?

**Comment by adamjmcgrath** [comment] 2023-01-03 10:45
Thanks for raising this @marcNY 

> I have added a rule to filter out users that are not set as active in app_metadata

`withMiddlewareAuthRequired` is designed to redirect the user to the login page if they are not authenticated and return them to the page they were trying to visit when login is successful.

If login is unsuccessful and you return to the page you were trying to visit, `withMiddlewareAuthRequired` will just redirect you to the login again, and since you have a session on auth0, you'll go straight to your rule - which presumably causes login to fail and start the loop again.

You can't expect the middleware to understand the difference between an anonymous user that has not attempted to login and an anonymous user that has attempted and failed to login.

You should either:

- Not use `withMiddlewareAuthRequired`
- Not use a rule which fails the login and instead look at https://auth0.github.io/nextjs-auth0/modules/handlers_callback.html#aftercallback for cancelling login

**Comment by marcNY** [comment] 2023-01-03 13:04
The second option would prevent me from taking advantage of Auth0 authorization rules. 

For the first option what would you recommend to protect all pages of the app?

**Comment by marcNY** [comment] 2023-01-03 13:11
> `withMiddlewareAuthRequired` is designed to redirect the user to the login page if they are not authenticated and return them to the page they were trying to visit when login is successful.
> 
> If login is unsuccessful and you return to the page you were trying to visit, `withMiddlewareAuthRequired` will just redirect you to the login again, and since you have a session on auth0, you'll go straight to your rule - which presumably causes login to fail and start the loop again.
> 
> You can't expect the middleware to understand the difference between an anonymous user that has not attempted to login and an anonymous user that has attempted and failed to login.
 
I am not having an infinite loop it is just that when the logging fail because of rules I have put in place in Auth0 the app work like if I was loggedin instead of sending me again to the Login page.

> You should either:
> 
> * Not use `withMiddlewareAuthRequired`
What should I use to protect all pages?

> * Not use a rule which fails the login and instead look at https://auth0.github.io/nextjs-auth0/modules/handlers_callback.html#aftercallback for cancelling login
With this option I won't be able to use authorization rules of Auth0 which defeat the purpose

**Comment by adamjmcgrath** [comment] 2023-01-05 15:15
> I am not having an infinite loop it is just that when the logging fail because of rules I have put in place in Auth0 the app work like if I was loggedin instead of sending me again to the Login page.

I'm not sure I understand exactly what you're trying to do and what the issue is - I don't understand how you expect "the app work like if I was loggedin" if login is failing due to your rule?

**Comment by marcNY** [comment] 2023-01-06 16:16
I am not expected the app to work as if I am logged in. I am expecting the app to redirect me to the login page. However it direct me automatically to an error page.

**Comment by adamjmcgrath** [comment] 2023-01-06 16:24
> I am expecting the app to redirect me to the login page. However it direct me automatically to an error page.

Ah, ok - I think I understand now. The default error handler will show an error page - if you want it to behave differently (say, redirect to a different page) all you need to do is override the default handler (the one for just the `callback` route or the `onError` one for all the auth routes), see https://github.com/auth0/nextjs-auth0/blob/main/EXAMPLES.md#customize-handlers-behavior for examples of how to customize the handler

**Comment by adamjmcgrath** [comment] 2023-01-20 11:46
I think https://github.com/auth0/nextjs-auth0/issues/984#issuecomment-1373862220 has answered your question, so closing

**Closed by adamjmcgrath** 2023-01-20 11:46 UTC
Labels: guidance
