### ISSUE TITLE
Works well in dev, but not in staging / production

### ISSUE THREAD

**Issue by imyjimmy** [auth0/nextjs-auth0#28] opened 2019-10-22 04:17 UTC
### Description

I have a Nextjs project where I followed the steps outlined in this README, and it works well locally. However, I'm using Serverless Framework to push to staging / production, and the login endpoint (the one that goes `https://mydomain.com/authorize?client_id=...`) shows `ERR_CONNECTION_REFUSED`

### Reproduction

In general, have a working Nextjs project without authentication, then:
1. Follow all the steps in the README
2. Try to deploy via Serverless Framework to AWS with `target: 'serverless'` in `next.config.js`

I will try to get a minimum reproducible repo up. In the meantime, I'm hoping that maybe there must be a configuration issue with my Auth0 app. But I have added my staging domain to the list of allowed callback urls.

### Environment

@auth0/nextjs-auth0 0.5.0
next 9.1.1
next-server 9.0.5
next-aws-lambda 2.3.4

Thanks

**Comment by sandrinodimattia** [comment] 2019-10-25 23:40
Hi @imyjimmy, if you could get us a repo to reproduce that would be great. I suspect this to be a configuration issue. The call to `/api/login` will initialize the client by executing some discovery steps. This will include making calls to some endpoints under `https://mydomain.com/...`.

You'll want to make sure your AWS Lambda can reach that server and that the environment variables are correctly set.

**Comment by sandrinodimattia** [comment] 2020-01-08 14:22
Closing this one since there hasn't been any activity in a while. Feel free to reopen the issue if you need more help.

**Closed by sandrinodimattia** 2020-01-08 14:22 UTC
