### ISSUE TITLE
You forgot to wrap your app in <UserProvider> in Next.js 14

### ISSUE THREAD

**Issue by mrcwinn** [auth0/nextjs-auth0#1557] opened 2023-11-10 15:07 UTC
### Checklist

- [X] The issue can be reproduced in the [nextjs-auth0 sample app](https://github.com/auth0-samples/auth0-nextjs-samples/tree/main/Sample-01) (or N/A).
- [X] I have looked into the [Readme](https://github.com/auth0/nextjs-auth0#readme), [Examples](https://github.com/auth0/nextjs-auth0/blob/main/EXAMPLES.md), and [FAQ](https://github.com/auth0/nextjs-auth0/blob/main/FAQ.md) and have not found a suitable solution or answer.
- [X] I have looked into the [API documentation](https://auth0.github.io/nextjs-auth0/) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/nextjs-auth0/issues) and have not found a suitable solution or answer.
- [X] I have searched the [Auth0 Community](https://community.auth0.com) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Description

I'm seeing the error "You forgot to wrap your app in <UserProvider>" in Next.js 14. My hunch is that it's related to server actions, which are no longer experimental.

### Reproduction

1. `npx create-next-app@latest`
2. Follow Auth0 QuickStart guide
3. `npm run dev`
4. Observe error

### nextjs-auth0 version

3.2.0

### Next.js version

14.0.2

### Node.js version

18.18.0

**Comment by adamjmcgrath** [comment] 2023-11-13 16:32
Hi @mrcwinn - thanks for raising this

It's unlikely to be Sever Actions since we don't include Server Actions in the QuickStart.

I can't reproduce your issue with the steps you've shared - could you share a repo that demonstrates the issue and I'd be happy to investigate

**Comment by adamjmcgrath** [comment] 2023-11-21 15:20
Closing, happy to reopen if you want to share a repo that demonstrates the issue

**Closed by adamjmcgrath** 2023-11-21 15:20 UTC
Labels: question
