### ISSUE TITLE
Blank page if error occurs in /app/auth/login

### ISSUE THREAD

**Issue by iant-ee** [auth0/nextjs-auth0#1304] opened 2023-07-20 09:06 UTC
### Checklist

- [X] The issue can be reproduced in the [nextjs-auth0 sample app](https://github.com/auth0-samples/auth0-nextjs-samples/tree/main/Sample-01) (or N/A).
- [X] I have looked into the [Readme](https://github.com/auth0/nextjs-auth0#readme), [Examples](https://github.com/auth0/nextjs-auth0/blob/main/EXAMPLES.md), and [FAQ](https://github.com/auth0/nextjs-auth0/blob/main/FAQ.md) and have not found a suitable solution or answer.
- [X] I have looked into the [API documentation](https://auth0.github.io/nextjs-auth0/) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/nextjs-auth0/issues) and have not found a suitable solution or answer.
- [X] I have searched the [Auth0 Community](https://community.auth0.com) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Description

If an error occurs on the /api/auth/login route, then the user just sees a blank page. There is no friendly error message, nor is there any debug information shown.

In my case the underlying error was "Discovery requests failing for https://foo.us.auth0.com, unable to get local issuer certificate" due to our corporate network configuration. But that's just one example. I'll use a different example in the reproduction.

### Reproduction

1. Get the sample app running normally
2. Use this as the contents of [auth0].js. Note the the code is intentionally broken (missing the import for handleLogin).

```import {handleAuth} from '@auth0/nextjs-auth0';

export default handleAuth({
    async login(req, res) {
        return handleLogin(req, res, {
        });
    }
});
```

3. Go to the sample app homepage
4. Click log in

Expected behaviour: Error message saying "handleLogin is not defined" OR a generic internal error page
Actual behaviour: Blank page

### nextjs-auth0 version

Tested on 2.0.0 and 4.0.0-beta.5

### Next.js version

13.1.0

### Node.js version

20

**Comment by adamjmcgrath** [comment] 2023-07-20 09:47
Hi @iant-ee - thanks for raising this

This is by design, the default error handler just logs the error in your server console and returns the http status.

You can use the `onError` handler to customise this behaviour (redirect, serve a specific ui, use a custom error logger, etc) see https://github.com/auth0/nextjs-auth0/blob/main/EXAMPLES.md#customize-handlers-behavior

**Comment by adamjmcgrath** [comment] 2023-07-25 10:32
Closing as I believe https://github.com/auth0/nextjs-auth0/issues/1304#issuecomment-1643615418 answers your question

**Closed by adamjmcgrath** 2023-07-25 10:32 UTC
Labels: question

**Comment by iant-ee** [comment] 2023-07-25 11:00
Thanks. I don't really understand why it's a blank page rather than using the default error handling of nextjs, but yes those docs will let me resolve the issue for my app. Thanks for your prompt response.
