### ISSUE TITLE
When building, I get the following error (Argument of type 'unknown' is not assignable to parameter of type 'Error | (Error & { _errors: Error[]; })')

### ISSUE THREAD

**Issue by froilanmmedina** [auth0/nextjs-auth0#1072] opened 2023-02-20 16:42 UTC
### Checklist

- [X] The issue can be reproduced in the [sample app](https://github.com/auth0-samples/auth0-nextjs-samples/tree/main/Sample-01) (or N/A).
- [X] I have looked into the [README](https://github.com/auth0/nextjs-auth0#readme) and have not found a suitable solution or answer.
- [X] I have looked into the [examples](https://github.com/auth0/nextjs-auth0/blob/main/EXAMPLES.md) and have not found a suitable solution or answer.
- [X] I have looked into the [API documentation](https://auth0.github.io/nextjs-auth0/) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/nextjs-auth0/issues) and have not found a suitable solution or answer.
- [X] I have searched the [Auth0 Community](https://community.auth0.com/c/sdks/5) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Description

When I build it, it shows me the following typescript error:  
 Argument of type 'unknown' is not assignable to parameter of type 'Error | (Error & { _errors: Error[]; })'
 ./node_modules/@auth0/nextjs-auth0/src/auth0-session/client.ts:58:32

```
55 try {
56      issuer = await Issuer.discover(config.issuerBaseURL);
57    } catch (e) {
58      throw new DiscoveryError(e, config.issuerBaseURL);
59    }
```

Variables defined in .env.local:
AUTH0_SECRET='myencryptsecret'
AUTH0_BASE_URL='http://localhost:3000'
AUTH0_ISSUER_BASE_URL='https://mydomain.com'
AUTH0_CLIENT_ID='myclientid'
AUTH0_CLIENT_SECRET='mysecret'
AUTH0_SCOPE='openid profile email read:current_user create:current_user_metadata update:current_user_metadata offline_access'
AUTH0_DOMAIN='mydomain.auth0.com'
AUTH0_AUDIENCE='myaudience'

### Reproduction

npm run build

### SDK version

2.2.1

### Next.js version

3.1.0

### Node.js version

v16.18.0

**Comment by Widcket** [comment] 2023-02-23 01:45
Hi @froilanmmedina, thanks for raising this.

Can you please confirm that this issue can be reproduced in the [sample app](https://github.com/auth0-samples/auth0-nextjs-samples/tree/main/Sample-01)?

I tried building the [kitchen sink example app](https://github.com/auth0/nextjs-auth0/tree/main/examples/kitchen-sink-example) and I was unable to reproduce:

<img width="649" alt="Screenshot 2023-02-22 at 22 44 10" src="https://user-images.githubusercontent.com/5055789/220803656-1a24e69f-083f-4a1f-ba52-50e96ad57707.png">

I'd suggest checking your TS version and configuration.

**Comment by froilanmmedina** [comment] 2023-02-24 21:15
Hi @Widcket, indeed the building of the example app was satisfactory. The problem seems to be associated with a typescript. I'm using version 4.9.4 currently.

**Comment by Widcket** [comment] 2023-02-24 21:18
Perfect, I'll go ahead and close this issue then, as it's not a bug in the SDK. Please let me know if you'd prefer to reopen.

**Closed** 2023-02-24 21:18 UTC
Labels: needs investigation

**Comment by froilanmmedina** [comment] 2023-02-25 02:54
Hello again @Widcket , after a while I managed to get rid of the previous error. Now, when babel update "isolatedModules": true in the tsconfig.js compulsorily, it generates the following error which I have not been able to avoid.

Re-exporting a type when the '--isolatedModules' flag is provided requires using 'export type'.
in ./node_modules/@auth0/nextjs-auth0/src/auth0-session/index.ts:9:27

Likewise when doing the build. Any idea about it?

**Comment by Widcket** [comment] 2023-02-27 21:15
@froilanmmedina that looks like a tooling configuration issue. Unfortunately we only use GH issues for bug reports or feature requests. For general usage questions please refer to the [Auth0 Community forums](https://community.auth0.com/c/sdks/5), or raise a support ticket.

**Comment by SkyM** [comment] 2024-08-05 04:02
For anybody else who runs into this error and finds this issue, the problem is probably a malformed import statement. 

i.e.

```
// Wrong 
import { GetAccessTokenResult } from '@auth0/nextjs-auth0/src/session/get-access-token'

// Right
import {GetAccessTokenResult} from '@auth0/nextjs-auth0'
```

My IDE snuck one of the incorrect imports into a file and this took me an embarrassingly long amount of time to hunt down.  This will cause both issues described in previous comments.
