### ISSUE TITLE
NextJS 13: support for server-side components in nextjs-auth0

### ISSUE THREAD

**Issue by freekh** [auth0/nextjs-auth0#889] opened 2022-10-28 13:01 UTC
### Checklist

- [X] I have looked into the [README](https://github.com/auth0/nextjs-auth0#readme) and have not found a suitable solution or answer.
- [X] I have looked into the [examples](https://github.com/auth0/nextjs-auth0/blob/main/EXAMPLES.md) and have not found a suitable solution or answer.
- [X] I have looked into the [API documentation](https://auth0.github.io/nextjs-auth0/) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/nextjs-auth0/issues) and have not found a suitable solution or answer.
- [X] I have searched the [Auth0 Community](https://community.auth0.com/c/sdks/5) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Describe the problem you'd like to have solved

Hello! 😃 
In order to support server-side components in NextJS 13, we think nextjs-auth0 needs it would be great to get the following changes. You might already have a roadmap for this. In that case, I guess you can close this issue.

## Support new 'next/headers' functions as params for getAccessToken 

Since req and res objects are not available in a server-side component, getAccessToken cannot be used with its current signature. A function that takes cookies() or headers() from the new 'next/headers' lib would work. 
We have a naive implementation for test-usage & fun here. It does not refresh tokens and has very little in the way of error management, so this more as an example of what we want:

```ts
import 'server-only';

import hkdf from 'futoin-hkdf';
import { JWE, JWK } from 'jose';
import { Cookies } from 'next/dist/server/web/spec-extension/cookies';
import { serversideConfig } from '../serversideConfig';  // we use this to handle missing env variables
import { logger } from './logger';  // our own logger implementation 

const BYTE_LENGTH = 32;
const ENCRYPTION_INFO = 'JWE CEK';
const options = { hash: 'SHA-256' };

/**
 *
 * Copied from @auth0/nextjs-auth0/src/auth0-session/utils/hkdf.ts
 */
const encryption = (secret: string): Buffer =>
  hkdf(secret, BYTE_LENGTH, { info: ENCRYPTION_INFO, ...options });

const alg = 'dir';
const enc = 'A256GCM';

/**
 * This should do the same as getAccessToken in @auth0/nextjs-auth0.
 *
 * We need this since, currently (2022-10-28), the getAccessToken function
 * needs req, res params, which server-components in Nextjs 13+ does not have (cookies() can be used instead).
 *
 * Also, importing @auth0/nextjs-auth0 fails with a 'react_1.createContext is not a function' error
 *
 * @param currentCookies using cookies()
 * @returns accessToken or undefined
 */
export const getAccessToken = async (
  currentCookies: Cookies
): Promise<string | undefined> => {
  const auth0Secret = serversideConfig.AUTH0_SECRET;
  const secretKey = JWK.asKey(encryption(auth0Secret));

  const getAppSessionNumber = (key: string) => {
    return parseInt(key.split('.')?.[1] || '-1', 10);
  };
  const appSessionKeys = Array.from(currentCookies.keys())
    .filter((key) => key.startsWith('appSession'))
    .sort((a, b) => {
      return getAppSessionNumber(a) - getAppSessionNumber(b);
    });
  const appSessions = appSessionKeys
    .map((key) => currentCookies.get(key))
    .flatMap((s) => (s ? [s] : []))
    .join('');
  if (!appSessions) {
    return undefined;
  }
  try {
    const jwt = await JWE.decrypt(appSessions, secretKey, {
      complete: true,
      contentEncryptionAlgorithms: [enc],
      keyManagementAlgorithms: [alg],
    });
    const jwtClearText = JSON.parse(jwt.cleartext.toString());
    return jwtClearText.accessToken;
  } catch (e) {
    logger.error('Error decrypting jwt', e);
    return undefined;
  }
};


```

## Fix `react_1.createContext is not a function error` on imports from '@auth0/nextjs-auth0'
This is a weird one, but if we import from ''@auth0/nextjs-auth0' in file that is used from a server-side component, we get the following error:

```
[0] Returning error page {
[0]   error: TypeError: react_1.createContext is not a function
[0]       at eval (webpack-internal:///(sc_server)/./node_modules/@auth0/nextjs-auth0/dist/frontend/use-config.js:8:22)
[0]       at (sc_server)/./node_modules/@auth0/nextjs-auth0/dist/frontend/use-config.js (/home/freekh/Code/folq/web/ts-frontend/.next/server/app/test/page.js:635:1)
[0]       at __webpack_require__ (/home/freekh/Code/folq/web/ts-frontend/.next/server/webpack-runtime.js:33:43)
[0]       at eval (webpack-internal:///(sc_server)/./node_modules/@auth0/nextjs-auth0/dist/frontend/index.js:11:20)
[0]       at (sc_server)/./node_modules/@auth0/nextjs-auth0/dist/frontend/index.js (/home/freekh/Code/folq/web/ts-frontend/.next/server/app/test/page.js:624:1)
[...redacted]
```

To reproduce, you can create a file: app/test/page.tsx:

```tsx
import {} from '@auth0/nextjs-auth0';

const Page = () => <div>Hello</div>;
export default Page;
```
And you enable appDir in the next.config.js file by for example putting the following in your NextJS 13 config:
```js
  experimental: {
    appDir: true,
  }
```

### Describe the ideal solution

A function which we can import to get the access tokens only using the headers() or cookies() from 'next/headers'.

### Alternatives and current workarounds

We have a work-around, but it is not production-grade.

**Comment by sesigl** [comment] 2022-10-29 05:23
Any updates? I would love to see a PR and be able to test it already.

**Comment by adamjmcgrath** [comment] 2022-10-31 17:31
Thanks for pointing that out @tmilewski 

I'll leave this open as an enhancement for adding server-side components support, but I don't have a timeline on when we'll be able to start working on this.

**Comment by TheodorRene** [comment] 2022-11-01 08:34
> The components are server components first, client second. Therefore you're attempting to load context on a server component which isn't going to work. You'll simply need to add `'use client';` to the top of the component using the context and you should be good to go with that issue.
> 

But we expect functions like `getAccessToken` and `getSession` to work fine on the server side. It is not expected that these functions attempt to load a context.  Is this not the case?

**Comment by tmilewski** [comment] 2022-11-01 09:06
> > The components are server components first, client second. Therefore you're attempting to load context on a server component which isn't going to work. You'll simply need to add `'use client';` to the top of the component using the context and you should be good to go with that issue.
> 
> > 
> 
> 
> 
> But we expect functions like `getAccessToken` and `getSession` to work fine on the server side. It is not expected that these functions attempt to load a context.  Is this not the case?
> 
> 

Nope, `getAccessToken` and `getSession` would not attempt to load the context on the server.

This is likely where `next/headers` would come in handy, as OP mentioned.

My original comment isn't meant to solve the RSC side of things but rather to illustrate that the context issue OP was having was due to the changes in how we now have to think about our components in Next 13.

**Comment by sesigl** [comment] 2022-11-01 18:25
I just want to highlight that the initial request of this PR is not addressed yet. But, it's quite important. Every next.js application that uses auth0 on the server side for components will be blocked due to that.

In next.js there is no server-side context with request and response anymore. Instead, there is:

- import { headers } from 'next/headers';
- import { cookies } from 'next/headers';

Though, the methods `getSessions` require a response and request object from the context.

I can imagine, an adapter might work. Not sure about the internal dependencies.

**Comment by AshSimmonds** [comment] 2022-11-05 23:27
Ok so forgive my fairly shallow understanding, but does this mean any page in Next13 RSC's which requires auth stuff will need to be `'use client'`'ed until the new 'mental model' is sussed out? Does that negate any of the potential benefits of the new ways, or am I ok to convert from using `pages` routing to `app` style?

**Comment by samakintunde37** [comment] 2022-11-06 22:46
> does this mean any page in Next13 RSC's which requires auth stuff will need to be `'use client'`'ed until the new 'mental model' is sussed out

Technically, yes and then we'd have to use a client-side `auth0` package. Currently, the method to get the `accessToken` on the server side takes `req` and `res` as arguments but we don't have access to those in Next13 components that live in the `app` directory.

> Does that negate any of the potential benefits of the new ways

Yes.

> am I ok to convert from using `pages` routing to `app` style

If you're using this library and would like to keep server components, probably not yet.

**Comment by ArielGueta** [comment] 2022-11-08 20:01
Following the nextjs tutorial and I still get the error.

```ts
// providers.tsx
"use client";

import { UserProvider } from "@auth0/nextjs-auth0";

export function Providers({ children }: any) {
  return <UserProvider>{children}</UserProvider>;
}

// layout.tsx
"use client";

import "./globals.css";
import { Providers } from "./providers";

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head />
      <body>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}

```

> TypeError: react_1.createContext is not a function

**Comment by ArielGueta** [comment] 2022-11-08 20:05
Actually, now I see that the issue is in the guard:

```ts
// page.tsx
"use-client";

import { withPageAuthRequired } from "@auth0/nextjs-auth0";

export default withPageAuthRequired(function Home() {
  return <h1>User</h1>;
});
```

This throws the error.

**Comment by ArielGueta** [comment] 2022-11-08 20:10
A workaround is to use the same technique and extract it an extra client component. Is there anyway to elegantly solve this issue?

**Comment by samakintunde37** [comment] 2022-11-08 20:58
Not yet, and doing it this way, you don't get the benefits of Server Components.

**Comment by ArielGueta** [comment] 2022-11-09 06:52
But we don't have a choice right now, no?

**Comment by samakintunde37** [comment] 2022-11-09 09:00
Not the best options but:
1. Update to Next13 and make everything client components
2. Stay on older Next and continue using library

2 is likely the better option for now, since you still get server-side auth and you can keep shipping. Still quite a number of bugs in Next13 with appDir feature being `experimental`.

**Comment by adamjmcgrath** [comment] 2022-11-09 09:41
> 1. Update to Next13 and make everything client components

You can also upgrade to Next 13 and continuing to use the pages directory rather than the experimental app directory

We will add support for server components, but it doesn't make sense for us to add it while the API is unstable. Also while we can't update the cookie to maintain our contract on offering a rolling session or have some sort of request context to cache the result of decrypting the cookie.

**Comment by dvh312** [comment] 2022-11-20 08:54
Using this as a workaround is good enough for me...

```tsx
import { cookies } from 'next/headers';

const Home = async () => {
  const res = await fetch(`${process.env.AUTH0_BASE_URL}/api/auth/me`, {
    headers: {
      cookie: `appSession=${cookies().get('appSession')?.value}`
    }
  })
  const user = await res.json()

  return (
    <p>
      {JSON.stringify(user)}
      <br/>
      <a href="/api/auth/login">LOG IN</a>
    </p>
  )
};

export default Home
```

**Comment by freekh** [comment] 2022-11-20 18:57
> Using this as a workaround is good enough for me...
> 
> ```tsx
> import { cookies } from 'next/headers';
> 
> const Home = async () => {
>   const res = await fetch(`${process.env.AUTH0_BASE_URL}/api/auth/me`, {
>     headers: {
>       cookie: `appSession=${cookies().get('appSession')?.value}`
>     }
>   })
>   const user = await res.json()
> 
>   return (
>     <p>
>       {JSON.stringify(user)}
>       <br/>
>       <a href="/api/auth/login">LOG IN</a>
>     </p>
>   )
> };
> 
> export default Home
> ```

If you are ok with doing an extra fetch, I suppose even just doing `fetch('/api/auth/me')`  (i.e. without the domain and headers) would work, since the cookie is already set?

Also, it is interesting that you can do `get('appSession')` on `Cookies`, but this might be us not looking carefully at how it works. I believe we got `appSession.0`, ... when we looked at it. When we looked at how it was implemented we saw that the lib does the same thing so never actually looked at the docs / implementation of `get`.

**Comment by dvh312** [comment] 2022-11-20 19:27
> > Using this as a workaround is good enough for me...
> > ```tsx
> > import { cookies } from 'next/headers';
> > 
> > const Home = async () => {
> >   const res = await fetch(`${process.env.AUTH0_BASE_URL}/api/auth/me`, {
> >     headers: {
> >       cookie: `appSession=${cookies().get('appSession')?.value}`
> >     }
> >   })
> >   const user = await res.json()
> > 
> >   return (
> >     <p>
> >       {JSON.stringify(user)}
> >       <br/>
> >       <a href="/api/auth/login">LOG IN</a>
> >     </p>
> >   )
> > };
> > 
> > export default Home
> > ```
> 
> If you are ok with doing an extra fetch, I suppose even just doing `fetch('/api/auth/me')` (i.e. without the domain and headers) would work, since the cookie is already set?
> 
> Also, it is interesting that you can do `get('appSession')` on `Cookies`, but this might be us not looking carefully at how it works. I believe we got `appSession.0`, ... when we looked at it. When we looked at how it was implemented we saw that the lib does the same thing so never actually looked at the docs / implementation of `get`.

True, can't really find Auth0 docs on the `appSession` cookie, so I updated the post to forward all cookies 😆 Also, I've tried `/api/auth/me` , fetch is throwing invalid URL 😛

**Comment by freekh** [comment] 2022-11-20 19:50
Ah, I forgot that this happens server-side so, it makes sense that my suggestions didn't work. Sorry about that!

**Comment by ScottAwesome** [comment] 2022-11-23 23:33
I like this idea, but won't the middleware make this sort of thing largely obsolete, which is due out in 2.0 correct?

**Comment by macrigiuseppe** [comment] 2022-11-27 14:43
hi Auth0 team,
thank you for the great contribution.

Having the ability to quickly integrate Auth0 with next.js is wonderful. it would be great to have the Auth0 SDK working out of the box with new next.js server components. It could save so much time to developers.
Do you have any update?

Thank you

**Comment by adamjmcgrath** [comment] 2022-11-28 09:09
Thanks for your interest @macrigiuseppe - see my comment here https://github.com/auth0/nextjs-auth0/issues/889#issuecomment-1308478322 - server components are experimental and we'll look into adding support when the api is stable

**Comment by focux** [comment] 2022-11-29 21:10
There are many of us already using Next.js 13, would be good if you could at least provide a workaround to make Auth0 work with server components.

**Comment by GryphonGroup** [comment] 2022-12-05 16:37
I'm gonna bump this one up. Auth0 is going to hold off our upgrade to Next.JS 13. It sounds like for a while. Hoping that we can avoid this as much as possible.

**Comment by adamjmcgrath** [comment] 2022-12-05 16:46
Thanks for your feedback @GryphonGroup - This SDK fully supports and is tested against Next.js 13. Could you share a little more about why support for (experimental) server-side components is blocking you from upgrading to Next.js 13?

**Comment by adamjmcgrath** [comment] 2022-12-05 18:19
> Is there anything we can be doing on our end to reduce the expected timeline to support server side components? 

Since Server Side Components are experimental (not to be used in production) - it's not just support from this SDK that should be blocking you from serving them to your customers.

Also, since the API for Server Side Components is unstable, it's reasonable for a downstream SDK to wait until it's stable before implementing it.

So, given that - the immediate thing that's blocking you from using Server Side components is Next.js officially supporting it (and once it's stable this SDK supporting it)

If you want to experiment with Server Side Components locally, v2.0.0 which has just been released will not fail when you import it into a Server Side Component (fixing the the 2nd part of the original issue raised) - it just doesn't support `next/headers` out of the box (for reasons I've explained https://github.com/auth0/nextjs-auth0/issues/889#issuecomment-1308478322).

You can see an experimental example that uses a workaround to get the session in a Server Component here https://github.com/auth0/nextjs-auth0/blob/main/examples/kitchen-sink-example/app/profile-experimental-rsc/page.tsx - but I must stress this is _experimental_, just to confirm that it is feasible - just like Next.js Server Components and the app directory, it should not be used in production.

**Comment by ysz** [comment] 2022-12-07 18:44
Thanks for the code @adamjmcgrath but I'm still getting this with your snippet

```
error - (sc_server)/node_modules/@auth0/nextjs-auth0/dist/frontend/use-config.js (6:21) @ eval
error - TypeError: react_1.createContext is not a function
```

**Comment by jackblackCH** [comment] 2022-12-25 23:49
> Using this as a workaround is good enough for me...
> 
> ```tsx
> import { cookies } from 'next/headers';
> 
> 
> const getUser = async () => {
>   const res = await fetch(`${process.env.AUTH0_BASE_URL}/api/auth/me`, {
>     headers: {
>       cookie: `appSession=${cookies().get('appSession')?.value}`
>       // cookie: cookies().getAll().map(c => `${c.name}=${c.value}`).join(';') -- all cookies
>     }
>   })
>   return await res.json()
> }
> 
> const Home = async () => {
>   const user = await getUser();
> 
>   return (
>     <p>
>       {JSON.stringify(user)}
>       <br/>
>       <a href="/api/auth/login">LOG IN</a>
>     </p>
>   )
> };
> 
> export default Home
> ```

+1 for this. works like a charm.

**Comment by haf** [comment] 2023-01-10 13:49
@adamjmcgrath The linked experimental rsc doesn't support `router.refresh()` properly; the code utilising the workaround doesn't refetch as per the docs https://beta.nextjs.org/docs/data-fetching/mutating

**Comment by Louis-Michalak** [comment] 2023-01-14 19:19
> Using this as a workaround is good enough for me...
> 
> ```tsx
> import { cookies } from 'next/headers';
> 
> 
> const getUser = async () => {
>   const res = await fetch(`${process.env.AUTH0_BASE_URL}/api/auth/me`, {
>     headers: {
>       cookie: `appSession=${cookies().get('appSession')?.value}`
>       // cookie: cookies().getAll().map(c => `${c.name}=${c.value}`).join(';') -- all cookies
>     }
>   })
>   return await res.json()
> }
> 
> const Home = async () => {
>   const user = await getUser();
> 
>   return (
>     <p>
>       {JSON.stringify(user)}
>       <br/>
>       <a href="/api/auth/login">LOG IN</a>
>     </p>
>   )
> };
> 
> export default Home
> ```

It will be a great solution until server side components are supported, but I'd suggest checking if appSession cookie exists before querying :
```typescript
import { UserProfile } from '@auth0/nextjs-auth0/client'

const getUser = async (): Promise<UserProfile | null> => {
  const sessionCookie = cookies().get('appSession')?.value
  if (sessionCookie === undefined) return null
  const res = await fetch(`${process.env.AUTH0_BASE_URL}/api/auth/me`, {
    headers: {
      cookie: `appSession=${sessionCookie}`,
      // cookie: cookies().getAll().map(c => `${c.name}=${c.value}`).join(';') -- all cookies
    },
  })
  return await (res.status === 200 ? res.json() : null)
}
```

**Comment by magnusriga** [comment] 2023-02-22 06:07
> > Using this as a workaround is good enough for me...
> > ```tsx
> > import { cookies } from 'next/headers';
> > 
> > 
> > const getUser = async () => {
> >   const res = await fetch(`${process.env.AUTH0_BASE_URL}/api/auth/me`, {
> >     headers: {
> >       cookie: `appSession=${cookies().get('appSession')?.value}`
> >       // cookie: cookies().getAll().map(c => `${c.name}=${c.value}`).join(';') -- all cookies
> >     }
> >   })
> >   return await res.json()
> > }
> > 
> > const Home = async () => {
> >   const user = await getUser();
> > 
> >   return (
> >     <p>
> >       {JSON.stringify(user)}
> >       <br/>
> >       <a href="/api/auth/login">LOG IN</a>
> >     </p>
> >   )
> > };
> > 
> > export default Home
> > ```
> 
> It will be a great solution until server side components are supported, but I'd suggest checking if appSession cookie exists before querying :
> 
> ```ts
> import { UserProfile } from '@auth0/nextjs-auth0/client'
> 
> const getUser = async (): Promise<UserProfile | null> => {
>   const sessionCookie = cookies().get('appSession')?.value
>   if (sessionCookie === undefined) return null
>   const res = await fetch(`${process.env.AUTH0_BASE_URL}/api/auth/me`, {
>     headers: {
>       cookie: `appSession=${sessionCookie}`,
>       // cookie: cookies().getAll().map(c => `${c.name}=${c.value}`).join(';') -- all cookies
>     },
>   })
>   return await (res.status === 200 ? res.json() : null)
> }
> ```

I tried this, and the original by @dvh312 , but for some reason the appSession cookie does not exist. I checked it in development ('npm run dev') and it does not work.

In short, I only do data fetching in Server Components, and wanted to check if a user that just sent a request is indeed logged in. I will use that check to conditionally render components (like navbar links), instead of using useUser(), because the latter relies on context and only works in client components.

Am I doing something wrong? Is Auth0 supposed to populate the cookies() with the appSession entry automatically?

**Comment by TheodorRene** [comment] 2023-02-22 07:37
@magnusriga See the first post by @freekh. There we use all the appSession cookies:
```ts
const getAppSessionNumber = (key: string) => {
    return parseInt(key.split('.')?.[1] || '-1', 10);
  };
  const appSessionKeys = Array.from(currentCookies.keys())
    .filter((key) => key.startsWith('appSession'))
    .sort((a, b) => {
      return getAppSessionNumber(a) - getAppSessionNumber(b);
    });
  const appSessions = appSessionKeys
    .map((key) => currentCookies.get(key))
    .flatMap((s) => (s ? [s] : []))
    .join('');
  if (!appSessions) {
    return undefined;
  }
```

**Comment by magnusriga** [comment] 2023-02-22 07:52
> @magnusriga See the original suggestion by @freekh. There we use all the appSession cookies:
> 
> ```ts
> const getAppSessionNumber = (key: string) => {
>     return parseInt(key.split('.')?.[1] || '-1', 10);
>   };
>   const appSessionKeys = Array.from(currentCookies.keys())
>     .filter((key) => key.startsWith('appSession'))
>     .sort((a, b) => {
>       return getAppSessionNumber(a) - getAppSessionNumber(b);
>     });
>   const appSessions = appSessionKeys
>     .map((key) => currentCookies.get(key))
>     .flatMap((s) => (s ? [s] : []))
>     .join('');
>   if (!appSessions) {
>     return undefined;
>   }
> ```

Thanks! I wrote the below in the meantime, but the suggestion you posted seems more dynamic. Do you know if it caches the result and that new requests use same cookie, or should we wrap it in Next.js's cache() function as described here: https://beta.nextjs.org/docs/data-fetching/caching#per-request-caching

```
const getUser = async () => {
  const sessionCookieArray = [
    cookies().get("appSession")?.value,
    cookies().get("appSession.0")?.value,
    cookies().get("appSession.1")?.value,
  ];

  const validCookie = sessionCookieArray
    .filter((sessionCookie) => Boolean(sessionCookie))
    .reduce(
      (cookie, currentSessionCookie, index, arr) =>
        `${cookie}appSession.${index}=${currentSessionCookie}${
          index + 1 <= arr.length ? ";" : ""
        }`,
      ``
    );

  const res = await fetch(`${process.env.AUTH0_BASE_URL}/api/auth/me`, {
    headers: {
      cookie: validCookie,
      // cookie: cookies().getAll().map(c => `${c.name}=${c.value}`).join(';') -- all cookies
    },
  });

  return await (res.status === 200 ? res.json() : null);
};
```

**Comment by magnusriga** [comment] 2023-02-25 18:58
@dvh312 / @TheodorRene I got the dvh312's suggestion to work in development mode (*npm run dev*), but when I tried to run it with *npm run build* + *npm run start*, I am getting the following error:

> TypeError: fetch failed
>     at Object.fetch (node:internal/deps/undici/undici:11118:11)  
>     at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
>   cause: Error: connect ECONNREFUSED ::1:3000
>       at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1300:16)
>       at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17) {
>     errno: -4078,
>     code: 'ECONNREFUSED',
>     syscall: 'connect',
>     address: '::1',
>     port: 3000
>   }
> }

Any idea what is going on here?

**Comment by TheodorRene** [comment] 2023-02-28 07:30
No idea, I just knew how to parse the appSession tokens. I would recommend to just use the `pages` directory until `app`/servercomponents etc are stable and supported by `nextjs-auth0`.

**Comment by magnusriga** [comment] 2023-02-28 08:30
> @dvh312 / @TheodorRene I got dvh312's suggestion to work in development mode (_npm run dev_), but when I tried to run it with _npm run build_ + _npm run start_, I am getting the following error:
> 
> > TypeError: fetch failed
> > at Object.fetch (node:internal/deps/undici/undici:11118:11)
> > at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
> > cause: Error: connect ECONNREFUSED ::1:3000
> > at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1300:16)
> > at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17) {
> > errno: -4078,
> > code: 'ECONNREFUSED',
> > syscall: 'connect',
> > address: '::1',
> > port: 3000
> > }
> > }
> 
> My fetch code is identical to dvh312's suggestion, I am forwarding all cookies for testing purposes.
> 
> A few notes:
> 
> * npm run start shows: _started server on 0.0.0.0:3000, url: http://localhost:3000_
> * When looking in the browser's DevTools, it actually shows the getUser fetch request with a 200 OK response, which I found weird because the browser should not do the fetch at all (it is just on the server, right?). Screen shot:
> 
> ![image](https://user-images.githubusercontent.com/38915578/221375060-cc9ddd0f-4bee-4bd7-8fa9-e1d064941337.png)
> 
> Any idea what is going on here?

@dvh312 Did you get your suggestion to work in production with a Next 13 site? Do you know how to solve the error above?

**Comment by macrigiuseppe** [comment] 2023-03-28 14:06
Hello Auth0,
With the NextJs App folder/server components being Beta, is there any development on supporting server components authentication within the SDK?

**Comment by adamjmcgrath** [comment] 2023-03-28 14:12
Hi @macrigiuseppe 👋 we have no plans to support the App Router feature while it is in Beta

**Comment by macrigiuseppe** [comment] 2023-03-28 15:07
@adamjmcgrath thank you for the quick response

**Comment by magnusriga** [comment] 2023-03-30 10:55
@Hav98ice I used middleware (handleAuth from Auth0) to guard segments, and 'use client' + useUser() to conditionally render nav links. Ideally, one would not have to rely on client-side rendering (useUser uses React context and can only be rendered client-side), but it is not a big issue. It works fine to let the nav links render client-side.

**Comment by magnusriga** [comment] 2023-03-30 11:17
@adamjmcgrath Slightly off-topic, but I spent some time on your source code (very impressive) and posted a question about it here: https://stackoverflow.com/questions/75818939/auth0-next-js-how-can-useuser-lookup-user-without-reading-cookies

If you have a spare minute sometime, I would deeply appreciate your input.

Thank you.

**Comment by jamesrweb** [comment] 2023-04-02 01:22
Since route handlers have been marked as stable in the NextJS 13 docs for a while now, can we assume work can begin on upgrading the project? or what's the current status of thought about this in the Auth0 team side of things?

<img width="592" alt="Bildschirm­foto 2023-04-02 um 03 18 58" src="https://user-images.githubusercontent.com/47126579/229325570-73e9b871-9e4b-40c9-bfa3-7f0436a997c5.png">

**Comment by jamesrweb** [comment] 2023-04-03 13:10
> Hi @jamesrweb - thanks for sharing that screenshot. I think it comes from here https://beta.nextjs.org/docs/app-directory-roadmap and I don't see anything that suggests the feature is stable.
> 
> 
> 
> I appreciate the enthusiasm, but please refer to my [earlier comment](https://github.com/auth0/nextjs-auth0/issues/889#issuecomment-1337896197) about our current status of thought.

As the docs say:

> As we push forward towards stability, this page will be updated with the latest information about the supported and unsupported features.

Once supported, it's stable. The unsupported features are the last required for the next 13 full release.

Since routes are marked as supported, it can be assumed they are stable.

Even if it was an experimental release version of this package. Otherwise we have to mix old and new api implementation styles and then client side authenticate always since server side props are no longer supported.

This is a very important use case for early adopters and those on the upgrade path, to which, this package is now a singular blocker to upgrading.

**Comment by magnusriga** [comment] 2023-04-04 00:12
> @dvh312 / @TheodorRene I got dvh312's suggestion to work in development mode (_npm run dev_), but when I tried to run it with _npm run build_ + _npm run start_, I am getting the following error:
> 
> > TypeError: fetch failed
> > at Object.fetch (node:internal/deps/undici/undici:11118:11)
> > at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
> > cause: Error: connect ECONNREFUSED ::1:3000
> > at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1300:16)
> > at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17) {
> > errno: -4078,
> > code: 'ECONNREFUSED',
> > syscall: 'connect',
> > address: '::1',
> > port: 3000
> > }
> > }
> 
> My fetch code is identical to dvh312's suggestion, I am forwarding all cookies for testing purposes.
> 
> A few notes:
> 
> * npm run start shows: _started server on 0.0.0.0:3000, url: http://localhost:3000_
> * When looking in the browser's DevTools, it actually shows the getUser fetch request with a 200 OK response, which I found weird because the browser should not do the fetch at all (it is just on the server, right?). Screen shot:
> 
> ![image](https://user-images.githubusercontent.com/38915578/221375060-cc9ddd0f-4bee-4bd7-8fa9-e1d064941337.png)
> 
> Any idea what is going on here?

In case others come across the issue above, the solution was to use the IPv4 address (http://127.0.0.1:3000) instead of http://localhost:3000 which seems to have defaulted to IPv6. Alternatively, place this at the top of the RSC:

```javascript
import dns from 'node:dns';
dns.setDefaultResultOrder('ipv4first');
```

**Source**: https://stackoverflow.com/questions/72390154/econnrefused-when-making-a-request-to-localhost-using-fetch-in-node-js

**Comment by JordanStuckings** [comment] 2023-04-07 04:01
> Hi @jamesrweb - thanks for sharing that screenshot. I think it comes from here https://beta.nextjs.org/docs/app-directory-roadmap and I don't see anything that suggests the feature is stable.
> 
> I appreciate the enthusiasm, but please refer to my [earlier comment](https://github.com/auth0/nextjs-auth0/issues/889#issuecomment-1337896197) about our current status of thought.

auth0 is the only thing holding me back from NextJS 13 launch. I'm probably just gonna swap over to firebase admin sdk.

**Comment by adamjmcgrath** [comment] 2023-04-11 11:00
Just to reiterate what I said in https://github.com/auth0/nextjs-auth0/issues/889#issuecomment-1337896197 

The app dir is _experimental_ (you get a warning when you enable it in your next.config.js and it's marked as beta in the [docs](https://beta.nextjs.org/docs))- this means that its api is unstable, it's not covered by semver, and may cause unexpected or broken application behavior - so should not be used in production. As soon as it is released as being stable, we will then prioritise the work to support it.

This SDK currently supports every _stable_ API in Next.js 13, so should not block you from adopting Next 13.

Locking this thread, rest assured as soon as the app directory is stable we will schedule some work to support it.

**Comment by adamjmcgrath** [comment] 2023-05-04 17:42
Closing in favour of https://github.com/auth0/nextjs-auth0/issues/1193

**Closed by adamjmcgrath** 2023-05-04 17:42 UTC
Labels: enhancement
