### ISSUE TITLE
getSession triggers sending data to the client

### ISSUE THREAD

**Issue by dariosky** [auth0/nextjs-auth0#616] opened 2022-03-15 11:17 UTC
I'm trying to create a thin proxy to use the session to get the apiToken and proxy to an internal API.
I'm using next-http-proxy-middleware to retrieve the session an add the Authorization header.
The issue is that whenever I call getSession (or getAccessToken) something is sent to the client, and setting a proxy-request header I get:

```
Cannot set headers after they are sent to the client
```

I also tried mocking the res parameter sent to getSession but without luck - how can I get the session readonly without interfering with the response?
I was also trying to read the cookie manually and using `jose` to decrypt it - but it seems an hack.

PS. I'm using Next.JS 12.1.0

Here's the code of my proxy

```js
/* pages/api/proxy/[...all].js */

import { getSession, withApiAuthRequired } from "@auth0/nextjs-auth0"
import httpProxyMiddleware from "next-http-proxy-middleware"
import { API_BASE } from "/utils/config"

export const config = {
  api: {
    bodyParser: false,
    externalResolver: true,
  },
}

const handleProxyInit = proxy => {
  proxy.once("proxyReq", async (proxyReq, req, res) => {
    // console.debug(`New request ${req.url}`)
    // console.log(req.cookies.appSession)
    let session = null
    session = await getSession(req, res)
    if (session?.user) {
      console.debug(`a request from ${session.user.name}-${session.user.sub}`)
    }
    const token = session?.accessToken
    if (token) {
      proxyReq.setHeader("Authorization", `Bearer ${token}`)
    }
  })
}

export default withApiAuthRequired(async (req, res) =>
  httpProxyMiddleware(req, res, {
    target: API_BASE,
    pathRewrite: [{ patternStr: "^/api/proxy", replaceStr: "" }],
    onProxyInit: handleProxyInit,
  }),
)
```

**Comment by adamjmcgrath** [comment] 2022-03-16 10:50
Hi @dariosky - this is currently by design. The session by default is a rolling session, so a new cookie expiry must be written to the response every time you get the session. 

We do have plans to change this behaviour to optionally only save on demand when you disable the rolling session option or when the session changes, but I can't give you a timeline on when this might happen.

Closing, feel free to ping me if you have any other questions

**Closed by adamjmcgrath** 2022-03-16 10:50 UTC
Labels: question

**Comment by dariosky** [comment] 2022-03-16 10:56
Thank you for the answer @adamjmcgrath 

If it can help - I ended up decoding the `req.cookies.appSession` manually (so to avoid the getSession).

```js
import hkdf from "futoin-hkdf"
import { JWK, JWE } from "jose"
import { strict as assert } from "assert"

const BYTE_LENGTH = 32
const ENCRYPTION_INFO = "JWE CEK"
const options = { hash: "SHA-256" }
const alg = "dir"
const enc = "A256GCM"

const secret = process.env.AUTH0_SECRET
const rollingDuration = process.env.AUTH0_SESSION_ROLLING_DURATION || 604800

const derivedKey = hkdf(secret, BYTE_LENGTH, { info: ENCRYPTION_INFO, ...options })
const epoch = () => (Date.now() / 1000) | 0 // eslint-disable-line no-bitwise

function verifyJWE(jweDecoded) {
  const { protected: header, cleartext } = jweDecoded
  const { iat, uat, exp } = header

  // check that the existing session isn't expired based on options when it was established
  assert(exp > epoch(), "it is expired based on options when it was established")

  // check that the existing session isn't expired based on current rollingDuration rules
  if (rollingDuration) {
    assert(uat + rollingDuration > epoch(), "it is expired based on current rollingDuration rules")
  }

  // check that the existing session isn't expired based on current absoluteDuration rules
  if (typeof absoluteDuration === "number") {
    assert(
      iat + absoluteDuration > epoch(),
      "it is expired based on current absoluteDuration rules",
    )
  }

  return JSON.parse(cleartext.toString())
}

export function decodeCookieSession(cookie) {
  return verifyJWE(
    JWE.decrypt(cookie, derivedKey, {
      complete: true,
      contentEncryptionAlgorithms: [enc],
      keyManagementAlgorithms: [alg],
    }),
  )
}
```

**Comment by adamjmcgrath** [comment] 2022-03-16 11:31
Yep - that's a good workaround for now, thanks for sharing @dariosky!

**Comment by adamjmcgrath** [comment] 2022-03-16 11:33
Just be aware that rolling sessions might not work as expected, if you never update the cookies expiration the `rollingDuration` of your session will effectively be the absolute duration (ie if your rollingDuration is set to 24hrs, the cookie will expire after 24hr regardless of the user's activity)

**Comment by jasdeepsingh** [comment] 2023-05-24 05:29
Facing this similar issue, is there a fix for this?
