### ISSUE TITLE
4.0.0-beta.2 getSession returns null

### ISSUE THREAD

**Issue by jimseiwert** [auth0/nextjs-auth0#1804] opened 2024-11-14 01:36 UTC
### Checklist

- [X] The issue can be reproduced in the [nextjs-auth0 sample app](https://github.com/auth0-samples/auth0-nextjs-samples/tree/main/Sample-01) (or N/A).
- [X] I have looked into the [Readme](https://github.com/auth0/nextjs-auth0#readme), [Examples](https://github.com/auth0/nextjs-auth0/blob/main/EXAMPLES.md), and [FAQ](https://github.com/auth0/nextjs-auth0/blob/main/FAQ.md) and have not found a suitable solution or answer.
- [X] I have looked into the [API documentation](https://auth0.github.io/nextjs-auth0/) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/nextjs-auth0/issues) and have not found a suitable solution or answer.
- [X] I have searched the [Auth0 Community](https://community.auth0.com) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Description

following the documentation on the readme for login. Everything works correctly redirecting to /auth/login and back. No errors on the callback. In the onCallback there is a session object. When you are on a server component and run the below code it returns null for the session

### Reproduction

1. setup per instructions on the [readme](https://github.com/auth0/nextjs-auth0/blob/v4/README.md)
2. go to child route using app router and use the following code
3. 

` import { auth0 } from "@/lib/auth0" `
 `  const session = await auth0.getSession()`
 `   return (
        <>
       <main>
          <h1>Welcome, {session.user.name}!</h1>
        </main>
    );`

### nextjs-auth0 version

4.0.0-beta.2

### Next.js version

15.0.3

### Node.js version

22.9.0

**Comment by guabu** [comment] 2024-11-14 08:02
Hey @jimseiwert 👋 The `getSession()` method returns `null` only if the user is not authenticated.

Could you share a complete minimal reproduction so I can help look into it? At first glance, nothing seems wrong with the snippet you shared but it's not enough to know what the setup looks like.

**Comment by jimseiwert** [comment] 2024-11-14 13:22
@guabu - Here you go, basic repo with the same behavior. [https://github.com/jimseiwert/redesigned-system](https://github.com/jimseiwert/redesigned-system)

**Comment by jimseiwert** [comment] 2024-11-14 14:45
Could it be an app setting in the dashboard I am missing? Here is a [screen recorder](https://go.screenpal.com/watch/cZX225nVXrD?_gl=1*dffrle*_ga*MTY5ODgwODY5Ni4xNzMxNTk1Mjg1*_ga_J7G603GGVL*MTczMTU5NTI4NC4xLjEuMTczMTU5NTQwNS4wLjAuMA..) of the behavior in chrome using the same repo I shared

**Comment by guabu** [comment] 2024-11-14 17:03
Thanks for the additional context.

> Could it be an app setting in the dashboard I am missing?

It should work on any new, default tenant — have you tried with another tenant just to rule that out?

Are you seeing any logs from your server or browser that might help narrow it down?

**Comment by jimseiwert** [comment] 2024-11-15 01:25
so a new tenant worked with no code changes. I am comparing the settings now to see if I can identify the difference.

**Comment by jimseiwert** [comment] 2024-11-15 02:34
Found the issue, looks like my tenant was set to an older version of node.... node 12 👎

Changing this to 18 fixed the error for me. Hope this helps someone else

**Comment by jimseiwert** [comment] 2024-11-15 03:42
I was wrong, that did not fix the issue, it was just a delay in the auth clearing. I am able to switch between the two tenants. One with a null session being returned and one that works (the new tenant). New apps in the old tenant do not work either. At a loss for what could be the cause.

**Comment by guabu** [comment] 2024-11-15 07:51
> so a new tenant worked with no code changes. I am comparing the settings now to see if I can identify the difference.

It seems that we've narrowed it down to the issue being related to the tenant setting.

Since it's an older tenant, there may be some setting at the tenant-level or client-level that might be causing this but I haven't managed to find the setting to reproduce this myself yet.

We're looking into this on our end — however, if you're able to share screenshots of your tenant and client level settings that would help me compare the settings. **Please make sure to redact any sensitive information before sharing.**

**Comment by jimseiwert** [comment] 2024-11-15 11:41
- Old tenant msc.auth0.com
- New tenant jimstest.us.auth0.com

I compared tenants and all the tenant setting and application level settings match each other. The only difference now is the tenant domains *.auth0.com vs *.us.auth0.com

IN v4 when I hook to the beforeSessionSaved hook and the onCallBack hook I see the session data. Just when I call await auth0.getSession() is it null for the old tenant. Is there a new data attribute the new tenant has that the old one does not that the sdk is looking for?

**Comment by VeigarMid** [comment] 2024-11-18 17:34
Same Issue here, using 4.0.0-beta.3. Happening on an older tenant as well, that is a Regular Web Application.

**Comment by guabu** [comment] 2024-11-19 07:47
@jimseiwert @VeigarMid after you've completed authentication, could you confirm if you have the `__session` cookie set with the following properties?

![cookies](https://github.com/user-attachments/assets/d73f0300-1855-482c-9df1-d802978284e0)

**Comment by jimseiwert** [comment] 2024-11-19 08:51
There is no cookie after login. I do see the seesion data in the onCallback(error, context, session) but no cookie is saved

**Comment by jimseiwert** [comment] 2024-11-19 11:36
Hi @guabu ,
I have found the cause. In our tenant we have an action that adds additional claims to the id and access token based on the user. When you have an action with the v4sdk that sets the accessToken it breaks the getSession call.

You can reproduce this by adding a post-login trigger event with the below code

```  api.accessToken.setCustomClaim(namespace + 'foo', event.user.name); ```

**Comment by jimseiwert** [comment] 2024-11-19 18:42
Hi @guabu, No, I keep using that sample since it has the bare minimum. I have noticed it is intermittent depending on when the action runs or not (event.authorization).

Would there be any settings I am overlooking for injecting additional claims at runtime? I tried even on the beforeSessionSave callback and had the same experience where I would see the session then add my claim and it would not save the cookie.

I also updated to beta 7 to see if that fixes some of the items. The same code base works on v3 of the sdk.

**Comment by jimseiwert** [comment] 2024-11-20 02:02
@guabu  - Happy to jump on a call or give you a test app in the tenant if you want to test side by side

**Comment by guabu** [comment] 2024-11-20 06:43
Hey @jimseiwert 👋

> I have noticed it is intermittent depending on when the action runs or not (event.authorization).

Based on this and that it occurs across all applications in this tenant but not the newly created tenant, I suspect this might be related to the Actions/Rules in your tenant adding additional data to the access token and causing it to go over the cookie size limit enforced by browsers (usually 4KB).

Could you:

1. Completely disable the Action and any Rules/Hooks you have for that tenant and let me know if this resolves the issue for you?
2. Share any extensibility code you have for that tenant (Actions, Rules, Hooks) — please be sure to redact any sensitive information.

> Would there be any settings I am overlooking for injecting additional claims at runtime? 

I believe it's not related to a specific setting but perhaps related to the above since the user can successfully authenticate but the cookie is not "sticking".

Thanks for being so patient while we try to get to the bottom of the issue 🙇 I understand the back-and-forth can be frustrating!

**Comment by ltatakis-optaxe** [comment] 2024-11-20 10:06
@guabu just to add here I am experiencing a similar problem.
We have a post login hook Action in Auth0 that adds three small custom claims

```
api.idToken.setCustomClaim(`.....roles`, assignedRoles)
api.idToken.setCustomClaim(`https://....com/organization`, event.organization)
....
```
then extract that data from the `user` returned in `useUser`.

Running the app on 3.5.0 I get the claims come through in the user data ( from the useUser hook ) but then moving to to 4.0.0-beta.7 none of them come through.

Same codebase, same tenant, same creds. 

Which as @jimseiwert mentions it either feels there is some new setting we are missing that we need to enable OR the lib is not pulling them through for some reason. Given you say you can see them, there must be some setting missing somewhere for this?

**Comment by guabu** [comment] 2024-11-20 10:17
Hey @ltatakis-optaxe 👋 This sounds like a separate issue here if I understand correctly. @jimseiwert is mentioning that the session cookie is not set after the user has authenticated whereas it seems in your case that the ID token does not get the custom claims set.

For the particular case your mentioning, you will need to use the `beforeSessionSaved` to propagate the claims to the user profile, like so:

```ts
export const auth0 = new Auth0Client({
  async beforeSessionSaved(session) {
    // filter out the claims however you like and set them on the user object
    return {
      ...session,
      user: {
        ...session.user,
        foo: "bar",
      },
    };
  },
});
```

This is documented here but perhaps we can make it more clear: https://github.com/auth0/nextjs-auth0/tree/v4?tab=readme-ov-file#beforesessionsaved

This is done to avoid adding all the ID token claims and bloating the cookie which was a common source of issues in v3.

**Comment by ltatakis-optaxe** [comment] 2024-11-20 10:28
@guabu that did indeed fix my issue. Thank you. Some better docs around that would be appreciated.

I  am sorry for side tracking the thread in this case.  🙇

**Comment by guabu** [comment] 2024-11-20 13:07
Definitely, I'll update the docs so it's more clear — thanks for the feedback!

**Comment by jimseiwert** [comment] 2024-11-21 18:31
Hi @guabu - after much digging we can close this issue as it is not a problem with the sdk.


> Based on this and that it occurs across all applications in this tenant but not the newly created tenant, I suspect this might be related to the Actions/Rules in your tenant adding additional data to the access token and causing it to go over the cookie size limit enforced by browsers (usually 4KB).


The above was the issue. It appears the old domain sent much more data with the token vs the new domain. I am not sure why it worked on v3 of the sdk but not v4 but that is a problem for a different day. After restructuring and removing the items I don't need use the beforesessionsaved event solved my issue. 

Thank you for the help troubleshooting this. Maybe a suggestion in the sdk would be to check the size and throw a warning/error if not created?

**Comment by guabu** [comment] 2024-11-22 07:12
Great! I'm glad we managed to get to the bottom of that one — sorry it took some time, it was a tricky one to track down!

> Thank you for the help troubleshooting this. Maybe a suggestion in the sdk would be to check the size and throw a warning/error if not created?

I definitely agree here, we'll need to show a warning so it's more clear and easier to troubleshoot. I'll make sure this gets added in the next release!

Thanks again for your patience throughout this!

**Comment by guabu** [comment] 2024-11-26 07:13
Warning log has been added to `v4.0.0-beta.8` when the cookie size exceeds 4096 bytes.

**Closed** 2024-11-26 08:05 UTC

**Comment by Inlustra** [comment] 2025-02-11 22:54
Hey guys, just been migrating over to V4 myself, just started to see some of the same sorts of issues. The warning does help, however in my case it's a little odd. 

I don't think I'm doing anything to particularly increase the size of the session data (And it was working correctly for me in v3 no issues) 

```
{
   "user": {
      "custom/email": "john.smith@example.com",
      "given_name": "John",
      "family_name": "Smith",
      "nickname": "john",
      "name": "John Smith",
      "picture": "https://lh3.googleusercontent.com/...REDACTED...",
      "updated_at": "2025-02-11T22:33:06.624Z",
      "email": "john.smith@example.com",
      "email_verified": true,
      "iss": "...REDACTED...",
      "aud": "...REDACTED...",
      "sub": "...REDACTED...",
      "iat": 1739313856,
      "exp": 1739314156,
      "sid": "...REDACTED...",
      "nonce": "...REDACTED..."
   },
   "tokenSet": {
      "accessToken": "...REDACTED...",
      "scope": "openid profile email offline_access",
      "refreshToken": "...REDACTED...",
      "expiresAt": 1739400256
   },
   "internal": {
      "sid": "...REDACTED...",
      "createdAt": 1739313856
   }
}
```

The only thing that appears rather large in this list, is the google picture, that's coming directly from Auth0 and Google, I don't really have any say on that one. 

The accessToken DOES have the permissions injected, totalling 1550 bytes. 

What is the work around? 

```
import { Auth0Client } from "@auth0/nextjs-auth0/server";

export const auth0 = new Auth0Client({
  beforeSessionSaved: async (sessionData, idToken) => {
    console.log(sessionData);
    delete sessionData.user.picture;
    return sessionData;
  },
  authorizationParameters: {
    audience: MY_AUDIENCE,
  },
});

```

At the moment, adding the above in to delete the picture does seem to do the trick, but this wasn't an issue before, so keen to understand what changed
