### ISSUE TITLE
App Router returns 500 Error

### ISSUE THREAD

**Issue by zeelmodi-simform** [auth0/nextjs-auth0#1336] opened 2023-08-01 11:21 UTC
### Checklist

- [X] The issue can be reproduced in the [nextjs-auth0 sample app](https://github.com/auth0-samples/auth0-nextjs-samples/tree/main/Sample-01) (or N/A).
- [X] I have looked into the [Readme](https://github.com/auth0/nextjs-auth0#readme), [Examples](https://github.com/auth0/nextjs-auth0/blob/main/EXAMPLES.md), and [FAQ](https://github.com/auth0/nextjs-auth0/blob/main/FAQ.md) and have not found a suitable solution or answer.
- [X] I have looked into the [API documentation](https://auth0.github.io/nextjs-auth0/) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/nextjs-auth0/issues) and have not found a suitable solution or answer.
- [X] I have searched the [Auth0 Community](https://community.auth0.com) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Description

I've freshly created a new set-up to integrated auth0 with Next.js and I'm constantly getting 500 HTTP error when visiting `/api/auth/login` route. I have also tried different installations of repositories on my machine but doesn't seems to be working with me.

Here what I get on my console:
`LoginHandlerError: Login handler failed. CAUSE: Discovery requests failing for https://dev-6vy0mwhhwzruj0vb.us.auth0.com, outgoing request timed out after 5000ms
    at eval (webpack-internal:///(rsc)/./node_modules/@auth0/nextjs-auth0/dist/handlers/login.js:60:19)
    at async eval (webpack-internal:///(rsc)/./node_modules/@auth0/nextjs-auth0/dist/handlers/auth.js:59:24)
    at async eval (webpack-internal:///(rsc)/./node_modules/next/dist/server/future/route-modules/app-route/module.js:253:37) {
  code: 'ERR_LOGIN_HANDLER_FAILURE',
  cause: DiscoveryError: Discovery requests failing for https://dev-6vy0mwhhwzruj0vb.us.auth0.com, outgoing request timed out after 5000ms
      at NodeClient.getClient (webpack-internal:///(rsc)/./node_modules/@auth0/nextjs-auth0/dist/auth0-session/client/node-client.js:47:19)
      at async NodeClient.authorizationUrl (webpack-internal:///(rsc)/./node_modules/@auth0/nextjs-auth0/dist/auth0-session/client/node-client.js:114:24)
      at async eval (webpack-internal:///(rsc)/./node_modules/@auth0/nextjs-auth0/dist/auth0-session/handlers/login.js:73:34)
      at async eval (webpack-internal:///(rsc)/./node_modules/@auth0/nextjs-auth0/dist/handlers/login.js:57:13)
      at async eval (webpack-internal:///(rsc)/./node_modules/@auth0/nextjs-auth0/dist/handlers/auth.js:59:24)
      at async eval (webpack-internal:///(rsc)/./node_modules/next/dist/server/future/route-modules/app-route/module.js:253:37),
  status: undefined
}`

For your information I'm on a free plan and recently signed up for auth0. I don't think it is an issue. Please help me here!

### Reproduction

1. The setup is really basic with Next.js app router and just created a button for login and I'm redirecting it on the `/api/auth/login`  route.
2. Created file `app/auth/[auth0]/route.ts` and added following:
````
export const GET = handleAuth({

    login: handleLogin({
        authorizationParams: {
            prompt: 'login'
        },
        returnTo: '/profile'
    }),
    signup: handleLogin({
        authorizationParams: {
            prompt: 'login',
            screen_hint:'signup'
        },
        returnTo: '/profile'
    })
});
````
3. Here is my .env file:
````
AUTH0_SECRET='REDACTED'
# AUTH0_SECRET='use [openssl rand -hex 32] to generate a 32 bytes value'
AUTH0_BASE_URL='http://localhost:3000'
AUTH0_ISSUER_BASE_URL='https://dev-6vy0mwhhwzruj0vb.us.auth0.com'
AUTH0_CLIENT_ID='aAhibbkJp6eelR0gGqDbKsHwtcHRK0ka'
AUTH0_CLIENT_SECRET='REDACTED'
````

4. served the app with npm run dev and clicked on login button and got the error

### nextjs-auth0 version

^3.0.1

### Next.js version

13.4.12

### Node.js version

v16.15.1

**Comment by adamjmcgrath** [comment] 2023-08-01 14:57
Hi @zeelmodi-simform - thanks for raising this

> Discovery requests failing for https://dev-6vy0mwhhwzruj0vb.us.auth0.com/, outgoing request timed out after 5000ms

This means that the request to your discovery document is timing out.

Since the document is there (here: https://dev-6vy0mwhhwzruj0vb.us.auth0.com/.well-known/openid-configuration) - it must mean that Node can't connect to the internet - this might be because it's behind a proxy

**Comment by zeelmodi-simform** [comment] 2023-08-02 07:31
Hey @adamjmcgrath , Thanks for your response. Can you suggest any way to resolve this?

**Comment by adamjmcgrath** [comment] 2023-08-02 09:43
@zeelmodi-simform what happens when you execute `node -e "require('https').get('https://www.google.com', res => console.log(res.statusMessage))"` in your terminal?

**Comment by zeelmodi-simform** [comment] 2023-08-02 09:45
@adamjmcgrath 
Here's attached screenshot:
![image](https://github.com/auth0/nextjs-auth0/assets/102504719/7e94939c-22fa-451e-8edc-3d4f2fbeecd9)

**Comment by adamjmcgrath** [comment] 2023-08-02 09:49
Can you also try `node -e "require('https').get('https://dev-6vy0mwhhwzruj0vb.us.auth0.com/.well-known/openid-configuration', res => console.log(res.statusMessage))"`

**Comment by zeelmodi-simform** [comment] 2023-08-02 09:50
Sure, here is what I'm getting:
![image](https://github.com/auth0/nextjs-auth0/assets/102504719/15854cc3-9fe1-4ef5-bf68-08249c802aac)

**Comment by adamjmcgrath** [comment] 2023-08-02 10:03
@zeelmodi-simform - sorry, I can't explain why Node can access that URL when run from your terminal but not when run from your Next app. Unfortunately, I'm not able to help you debug a networking issue on your machine

**Comment by zeelmodi-simform** [comment] 2023-08-02 10:23
@adamjmcgrath Would you mind testing this repository for me? https://github.com/zeelmodi-simform/nextjs-sso-implementation-poc
You just need to navigate to [login](http://localhost:3000/login)

**Comment by adamjmcgrath** [comment] 2023-08-02 10:34
Hi @zeelmodi-simform - I've just tested your app and I'm able to successfully login (you should see a successful login from foo@example.com in your tenant logs)

The request is a regular Node request being made from here https://github.com/panva/node-openid-client/blob/v5.4.3/lib/helpers/request.js#L120

Network timeouts from the local machine are usually caused by endpoint protection software on the machine like ZScaler or some environmental proxy issues. (Although I can't explain why the request works from `node -e`)

You should also try restarting your server if you haven't already, the bad response might be cached somehow

**Comment by zeelmodi-simform** [comment] 2023-08-02 10:38
@adamjmcgrath Thank you so much for all your help and testing the app for me. I have tried testing it with Firefox and Chrome both, even tested out repositories I found online. But nothing is working for me. I've restarted my system thrice since yesterday. I will now dig deeper into it to resolve networking issue. I really appreciate your help here!

**Comment by adamjmcgrath** [comment] 2023-08-03 10:32
> To check if it only having problems with my local machine, I had also deployed it to vercel but getittng same issue over there as well. Here is the link for the live deployment: [nextjs-sso-implementation-poc.vercel.app](https://nextjs-sso-implementation-poc.vercel.app/)

@zeelmodi-simform - could you share the error you're getting in the logs from visiting https://nextjs-sso-implementation-poc.vercel.app/api/auth/login ?

**Comment by zeelmodi-simform** [comment] 2023-08-03 10:35
Sure, Here are the logs from vercel:
```
LoginHandlerError: Login handler failed. CAUSE: Discovery requests failing for https://https://dev-6vy0mwhhwzruj0vb.us.auth0.com, getaddrinfo ENOTFOUND https
    at /var/task/.next/server/chunks/877.js:1999:19
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async /var/task/.next/server/chunks/877.js:1762:24
    at async /var/task/.next/server/chunks/501.js:5757:37 {
  code: 'ERR_LOGIN_HANDLER_FAILURE',
  cause: DiscoveryError: Discovery requests failing for https://https://dev-6vy0mwhhwzruj0vb.us.auth0.com, getaddrinfo ENOTFOUND https
      at NodeClient.getClient (/var/task/.next/server/chunks/877.js:74:19)
      at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
      at async NodeClient.authorizationUrl (/var/task/.next/server/chunks/877.js:141:24)
      at async /var/task/.next/server/chunks/877.js:515:34
      at async /var/task/.next/server/chunks/877.js:1996:13
      at async /var/task/.next/server/chunks/877.js:1762:24
      at async /var/task/.next/server/chunks/501.js:5757:37,
  status: undefined
}

```

**Comment by adamjmcgrath** [comment] 2023-08-03 10:38
> Discovery requests failing for https://https://dev-6vy0mwhhwzruj0vb.us.auth0.com/

What value are you setting for `issuerBaseUrl`? The Discovery request starts with `https://https://...`

**Comment by zeelmodi-simform** [comment] 2023-08-03 10:39
> > Discovery requests failing for https://https://dev-6vy0mwhhwzruj0vb.us.auth0.com/
> 
> What value are you setting for `issuerBaseUrl`? The Discovery request starts with `https://https://...`

https://https://dev-6vy0mwhhwzruj0vb.us.auth0.com

**Comment by adamjmcgrath** [comment] 2023-08-03 10:41
> `https://https://dev-6vy0mwhhwzruj0vb.us.auth0.com`

☝️ It only needs one `https://`

**Comment by zeelmodi-simform** [comment] 2023-08-03 10:42
Sorry, my bad

**Comment by zeelmodi-simform** [comment] 2023-08-03 10:45
@adamjmcgrath It now works for me after deployment, but the real question is still there why it isn't working on my system ?!?!?

**Comment by adamjmcgrath** [comment] 2023-08-03 10:47
@zeelmodi-simform - See my suggestions here https://github.com/auth0/nextjs-auth0/issues/1336#issuecomment-1661967741. I can't fix a networking issue on your machine. I see login is working now on `nextjs-sso-implementation-poc.vercel.app` so am going to close this.

**Closed by adamjmcgrath** 2023-08-03 10:47 UTC
Labels: question
