### ISSUE TITLE
Bad error handling - `checks.state argument is missing`

### ISSUE THREAD

**Issue by KATT** [auth0/nextjs-auth0#391] opened 2021-05-07 11:56 UTC
### Describe the problem

Error handling doesn't seem that graceful - simply ending up on a blank page on `/callback` that just says `checks.state argument is missing`.

### What was the expected behavior?

Probably needs to be passed back to some sort of error handling

### Reproduction

1. Disable signups in Auth0
2. Add api following api route called `/signup`:
  ```ts
  import { handleLogin } from '@auth0/nextjs-auth0';
  import { NextApiRequest, NextApiResponse } from 'next';

  export default async function registerHandler(
    req: NextApiRequest,
    res: NextApiResponse,
  ) {
    handleLogin(req, res, {
      authorizationParams: {
        screen_hint: 'signup',
      },
    });
  }
  ```
3. Go to `/api/signup`

### Environment

- **Version of this library used:** 1.2.0
- **Which framework are you using, if applicable:** next.js
- **Other modules/plugins/libraries that might be involved:**
- **Any other relevant information you think would be useful:**

**Comment by adamjmcgrath** [comment] 2021-05-10 09:07
@KATT - am closing this as I think I've answered your question. Feel free to ping me if you'd like me to reopen

**Comment by KATT** [comment] 2021-05-11 12:45
@adamjmcgrath would like to keep it open - I've had this happen in production a few times but I don't know the cause

**Comment by KATT** [comment] 2021-05-11 12:46
When does `checks.state argument is missing` happen? I get it after a user signup sometimes

**Comment by adamjmcgrath** [comment] 2021-05-11 15:44
@KATT 

When you visit `/api/auth/login` the SDK drops a `state` cookie (amongst others), and redirects you to the authorization server to login. When login completes the authorization server redirects you to `/api/auth/callback` and the SDK picks up the `state` cookies and verifies it matches the state parameter in the callback request before logging you in.

If the SDK can't find the `state` cookie when it goes to pick it up, it throws `checks.state argument is missing`. This can happen due to a login concurrency issue (see [this FAQ](https://github.com/auth0/nextjs-auth0/blob/main/FAQ.md#1-why-do-i-get-a-checks.state-argument-is-missing-error-if-i-try-to-log-in-from-different-tabs)) or because the cookie can't be read for some other reason (it's set on the wrong path, domain, with `SameSite=Strict`)

**Comment by KATT** [comment] 2021-05-12 18:49
Also I get this in cypress a lot when doing login there , those docs might help, will look, thanks 👀

**Comment by adamjmcgrath** [comment] 2021-05-25 09:39
@KATT If you're still seeing this issue in Cypress and can share a simple project to reproduce the issue, I'd be happy to debug it for you.

Closing this, feel free to ping me if you'd like me to reopen.

**Closed by adamjmcgrath** 2021-05-25 09:39 UTC
Labels: question

**Comment by monarchwadia** [comment] 2021-07-09 00:16
Just some feedback. A client pointed out this issue on their app . 

 It took my team ~7 days and 2 developers (on-and-off.. so total maybe 10 hours to 20 hours) to diagnose and fix this error. 

A better error message would have saved us a ton of time.

**Comment by adamjmcgrath** [comment] 2021-07-12 08:51
Thanks for the feedback @monarchwadia - cold you tell me a bit more about the issue you were facing and what sort of error message might have helped you diagnose it faster?

**Comment by monarchwadia** [comment] 2021-07-12 12:50
We were given a bug report and, while trying to reproduce that bug report, were able to land on this page frequently when visiting it through a stale auth callback link (`/api/auth/callback?code=_____&state=_____`). We are not sure how/why the reporter kept visiting the auth link, just that they did. Googling for "checks.state argument is missing" was very unhelpful and did not lead us to the right solution or documentation.

**Suggestion for improved experience**

**In development:**
A React Overlay style error message would help a lot.  When `NODE_ENV != production`, we should see a default error handling template. The template should state clearly that it is a template, and that the error originated deep in the stack. It would be amazing to show the stack itself and provide more info.  See screenshot below.

![image](https://user-images.githubusercontent.com/4856944/125290084-ef02d980-e2ed-11eb-9102-5140cf1733e2.png)

**In production:**
Using Auth0's own styling, but with the user's organization's logo (if set), simply explain that an unknown error has occurred. This will save face for many service firms like ours who are using Auth0.

I hope this helps :-)

**Comment by FDiskas** [comment] 2021-09-13 19:26
I also opened this repository and tried to run e2e tests and got the same problem
![Screenshot from 2021-09-13 22-25-16](https://user-images.githubusercontent.com/468006/133144413-4c2d052b-59d6-4720-92d6-e476e452a7b7.png)

**Comment by SpencerKaiser** [comment] 2022-02-01 21:50
@monarchwadia you're a LEGEND for sharing this:
>We were given a bug report and, while trying to reproduce that bug report, were able to land on this page frequently when visiting it through a stale auth callback link (`/api/auth/callback?code=_____&state=_____`). 

@adamjmcgrath thanks for the awesome package, it's been tremendously helpful. I want to echo a lot of the sentiment @monarchwadia said above. I just showed my site to someone for the first time ever and they hit this issue ☹️ I tried to login using their credentials and couldn't replicate it but they had 100% success replicating across all browsers, so I decided to send them the logout URL and after logout/login, they were able to sign in successfully. So I feel like it must be some funky timing issue (I'm about to dig into the docs you posted above and see if anything in there is relevant).

That being said, I still think there's a better way of addressing this for other devs because it's been pretty painful to research and I was lucky to stumble on this issue (after reading 3-4 others that were all close but less relevant 😅). I also think some docs around best practices for handling this would be immensely helpful. My thought now is to add custom error handling for that specific issue (thanks again for the repro URL, @monarchwadia!!!!!) simply redirect the user to an unprotected page that asks them to logout and log back in and that we apologize for the inconvenience on that page. Any other ideas?

**Comment by monarchwadia** [comment] 2022-02-01 21:59
@SpencerKaiser I'm glad I was able to save you & others from this painful, painful issue :-D 

 I can't remember now..... but I think what we did was actually invalidate the session somehow, thus side-stepping this issue?

**Comment by SpencerKaiser** [comment] 2022-02-01 22:21
Alright I've been playing around with the docs for [custom behavior](https://github.com/auth0/nextjs-auth0/blob/main/EXAMPLES.md#customize-handlers-behavior) and I can't for the life of me figure out where that error gets intercepted; following those docs don't yield any changes ☹️ any suggestions on where to look?

**Comment by monarchwadia** [comment] 2022-02-01 22:44
Have you tried wrapping it in a try catch?

**Comment by SpencerKaiser** [comment] 2022-02-01 22:48
The issue is that I was/am dumb. I literally just figured it out and was coming back to post an update.

I'm still new to auth so some of this stuff is tricky for me, but I didn't know that `handleAuth` could take other args beyond `login` and obviously this issue is taking place on the callback side. Here's what I just setup:


`/pages/api/auth/[...auth0].ts`
``` typescript
/* istanbul ignore file */
import { handleAuth, handleCallback } from '@auth0/nextjs-auth0';

export default handleAuth({
  async callback(req, res) {
    try {
      await handleCallback(req, res);
    } catch (error) {
      res.redirect('/error');
    }
  },
});
```

Meanwhile on the frontend, here's the experience for users (`Try Again` redirects to `/api/auth/login`):
![image](https://user-images.githubusercontent.com/6445731/152064280-1d06e4ac-b8df-4f5a-ac5e-c430dae16307.png)

If you can remember what you did to make the experience a little cleaner for the user (ideally not even show them that page), I'm all ears!

**Comment by monarchwadia** [comment] 2022-02-02 00:29
Why not just redirect to `/api/auth/login` when you catch, instead of going to `/error`? I think that's what we did

**Comment by SpencerKaiser** [comment] 2022-02-02 00:41
I thought about doing that, but couldn't you potentially create an infinite loop if Auth0 is having trouble? Even if I check for the status, I'm still a little skittish of doing that automatically 🤔

**Comment by monarchwadia** [comment] 2022-02-02 04:10
Yes, that's why you invalidate the session before redirect

**Comment by SpencerKaiser** [comment] 2022-02-03 19:30
Invalidate the session server side or client side? I'm struggling to find docs about how to do that...

**Comment by monarchwadia** [comment] 2022-02-03 19:53
Oh I just clear cookies or localstorage manually

**Comment by FatehAK** [comment] 2023-07-27 08:47
Hey @monarchwadia and @SpencerKaiser I'm facing the same issue. Is it not possible to invalidate the session programatically? I could redirect the user to a logout route but I'd prefer to clear the session via code and redirect the user to login.

**Comment by SpencerKaiser** [comment] 2023-08-23 17:46
@FatehAK sorry for the delay, I missed this in my inbox. I unfortunately gave up on Auth0; I was never able to find a solution and it was just too much of a burden. Switched to Twilio's verify solution and went passwordless 👀
