### ISSUE TITLE
Error: You forgot to wrap your app in <UserProvider> when using Head from 'next/head'

### ISSUE THREAD

**Issue by exipnus** [auth0/nextjs-auth0#582] opened 2022-01-23 11:34 UTC
Hi,

The following error occurs  when using next/head in both the index.tsx (Home) page and the _document.sx page:

![image](https://user-images.githubusercontent.com/85255193/150677913-4f4ca7c5-88bd-4ec9-9e15-1a23805fda65.png)

_document.tsx
```js
import createEmotionServer from '@emotion/server/create-instance';
import theme from '@theme';
import createEmotionCache from '@theme/createEmotionCache';
import Document, { Head, Html, Main, NextScript } from 'next/document';
import * as React from 'react';

export default class MyDocument extends Document {
  render() {
    return (
      <Html lang="en">
        <Head key="document-head">
          {/* PWA primary color */}
          <meta name="theme-color" content={theme.palette.primary.main} />
          <link rel="preconnect" href="https://fonts.googleapis.com" />
          <link
            rel="preconnect"
            href="https://fonts.gstatic.com"
            crossOrigin="true"
          />
          <link
            href="https://fonts.googleapis.com/css2?family=Comfortaa:wght@700&family=Work+Sans:ital,wght@0,100;0,200;0,300;0,400;1,100;1,200;1,300;1,400&display=swap"
            rel="stylesheet"
          />
        </Head>
        <body>
          <Main />
          <NextScript />
          <div id="snackbar-root"></div>
        </body>
      </Html>
    );
  }
}

// `getInitialProps` belongs to `_document` (instead of `_app`),
// it's compatible with static-site generation (SSG).
MyDocument.getInitialProps = async (ctx) => {
  // Resolution order
  //
  // On the server:
  // 1. app.getInitialProps
  // 2. page.getInitialProps
  // 3. document.getInitialProps
  // 4. app.render
  // 5. page.render
  // 6. document.render
  //
  // On the server with error:
  // 1. document.getInitialProps
  // 2. app.render
  // 3. page.render
  // 4. document.render
  //
  // On the client
  // 1. app.getInitialProps
  // 2. page.getInitialProps
  // 3. app.render
  // 4. page.render

  const originalRenderPage = ctx.renderPage;

  // You can consider sharing the same emotion cache between all the SSR requests to speed up performance.
  // However, be aware that it can have global side effects.
  const cache = createEmotionCache();
  const { extractCriticalToChunks } = createEmotionServer(cache);

  ctx.renderPage = () =>
    originalRenderPage({
      // eslint-disable-next-line react/display-name
      enhanceApp: (App: any) => (props) =>
        <App emotionCache={cache} {...props} />,
    });

  const initialProps = await Document.getInitialProps(ctx);
  // This is important. It prevents emotion to render invalid HTML.
  // See https://github.com/mui-org/material-ui/issues/26561#issuecomment-855286153
  const emotionStyles = extractCriticalToChunks(initialProps.html);
  const emotionStyleTags = emotionStyles.styles.map((style) => (
    <style
      data-emotion={`${style.key} ${style.ids.join(' ')}`}
      key={style.key}
      // eslint-disable-next-line react/no-danger
      dangerouslySetInnerHTML={{ __html: style.css }}
    />
  ));

  return {
    ...initialProps,
    // Styles fragment is rendered after the app and page rendering finish.
    styles: [
      ...React.Children.toArray(initialProps.styles),
      ...emotionStyleTags,
    ],
  };
};
```

_app.tsx

```js
import '../styles/globals.css';

import { UserProvider } from '@auth0/nextjs-auth0';
import { AppProps } from 'next/app';

const MyApp = ({ Component, pageProps }: AppProps) => {
  return (
    <UserProvider>
      <Component {...pageProps} />
    </UserProvider>
  );
};

export default MyApp;
```

index.tsx

```js
import { NextPage } from 'next';
import Head from 'next/head';
import React, { Fragment } from 'react';

const HomePage: NextPage = () => {
  return (
    <Fragment>
      <Head>
        <title>Home Page</title>
      </Head>
      <div>Home Page</div>
    </Fragment>
  );
};

export default HomePage;
```

Upon removing the Head component from either the index.tsx or the _document.tsx  page the error goes away.
When using it on both pages the error shows up when refreshing the page.

Thank you

**Comment by Widcket** [comment] 2022-01-25 01:06
Hi @exipnus, thanks for raising this.

Are you able to reproduce this on the Next.js SDK [sample app](https://github.com/auth0-samples/auth0-nextjs-samples/tree/main/Sample-01)?

**Comment by Widcket** [comment] 2022-01-25 01:07
Also, please, fill in all the fields of the [issue template](https://github.com/auth0/nextjs-auth0/blob/main/.github/ISSUE_TEMPLATE/report_a_bug.md).

**Comment by snaqu** [comment] 2022-01-31 08:57
I had the same issue and rm -rf node_modules and cache clean did a job

**Comment by adamjmcgrath** [comment] 2022-01-31 13:56
@exipnus let us know if that resolves your issue or if you can reproduce the issue on the sample app

**Comment by nliapis** [comment] 2022-02-02 20:23
Had the same issue when I upgraded the node v14.x.x to v16..13.2.
Fixed when I downgraded back to to v14.

**Comment by Widcket** [comment] 2022-02-08 22:37
Looks like this is not an issue with the SDK. I'll close this issue, @exipnus please let me know if you'd prefer to reopen.

**Closed by Widcket** 2022-02-08 22:37 UTC
Labels: needs investigation

**Comment by lakshmankashyap** [comment] 2022-10-20 12:12
Hi, how can i get accesstoken in next for axios call

**Comment by netergart** [comment] 2023-02-02 17:57
@Widcket I have the same issue when use `next/head` somewhere? did somebody know how fix this?

**Comment by Alarid** [comment] 2023-02-16 08:47
+1, I have been having this issue for ages now, my console is filled with this error. I do not wish to downgrade node nor to change the way I use <Head />. @Widcket I do think this is an issue with the SDK: it shouldn't log an error AND work normally at the same time, this is very confusing

**Comment by subnetmarco** [comment] 2023-04-13 01:27
Having this issue with node v18.x

**Comment by dlarroder** [comment] 2023-04-28 03:14
Is there an update on this? Can someone re-open as it seems to still be an issue

**Comment by masakudamatsu** [comment] 2023-05-10 23:33
I keep getting this error `You forgot to wrap your app in <UserProvider>` when I test the app with Cypress and Testing Library. It's rather random when this error occurs. The same query (`cy.findByRole('button', {name: 'Osen'})`, for example) sometimes returns this error while it doesn't in other times.

Here's the error stack trace:
```
at get error [as error] ([webpack-internal:///./node_modules/@auth0/nextjs-auth0/dist/frontend/use-user.js:43:15](http://localhost:3000/__/#))
From previous event:
    at whenStable (http://localhost:3000/__cypress/runner/cypress_runner.js:152819:65)
    at <unknown> (http://localhost:3000/__cypress/runner/cypress_runner.js:152244:14)
```

**Comment by fuadsaud** [comment] 2023-09-07 16:12
This issue happens consistently for me with latest version of the SDK (3.1.0) and with node v18.13. I'm having trouble understanding what exactly is the code path that triggers it, but it does seem to be a problem with the SDK.

**Comment by sranso** [comment] 2023-09-08 15:50
@Widcket @adamjmcgrath Hello! I was experiencing this issue on my own app, and followed the instructions to try to repro on the sample app. I did so and am seeing the issue there as well. I've simply cloned, `yarn install`d, changed it to run on port `4000` (to match my Auth0 added my Auth0 info). 

Let me know if I'm missing something / if there's a fix! 🙇‍♀️ 
<img width="991" alt="Screenshot 2023-09-08 at 11 45 37 AM" src="https://github.com/auth0/nextjs-auth0/assets/4968408/deffc432-8917-4a10-81d6-1153ee0ff102">

**Comment by boiboiler** [comment] 2023-09-15 05:41
I have same error!!
any update?

```
Error: You forgot to wrap your app in <UserProvider>
    at get user [as user] (webpack-internal:///(:5300/app-pages-browser)/./node_modules/@auth0/nextjs-auth0/dist/client/use-user.js:38:15)
    at JSON.stringify (<anonymous>)
    at Object.parseData (<anonymous>:8:116)
    at <anonymous>:10:2186
    at Array.reduce (<anonymous>)
    at <anonymous>:10:2114
    at i (<anonymous>:10:2706)
    at t.onCommitFiberRoot.t.onCommitFiberRoot (<anonymous>:10:3098)
    at onCommitRoot$1 (webpack-internal:///(:5300/app-pages-browser)/./node_modules/next/dist/compiled/react-dom/cjs/react-dom.development.js:669:22)
    at commitRootImpl (webpack-internal:///(:5300/app-pages-browser)/./node_modules/next/dist/compiled/react-dom/cjs/react-dom.development.js:25060:3)
    at commitRoot (webpack-internal:///(:5300/app-pages-browser)/./node_modules/next/dist/compiled/react-dom/cjs/react-dom.development.js:24846:5)
    at commitRootWhenReady (webpack-internal:///(:5300/app-pages-browser)/./node_modules/next/dist/compiled/react-dom/cjs/react-dom.development.js:23584:3)
    at finishConcurrentRender (webpack-internal:///(:5300/app-pages-browser)/./node_modules/next/dist/compiled/react-dom/cjs/react-dom.development.js:23549:5)
    at performConcurrentWorkOnRoot (webpack-internal:///(:5300/app-pages-browser)/./node_modules/next/dist/compiled/react-dom/cjs/react-dom.development.js:23394:9)
    at workLoop (webpack-internal:///(:5300/app-pages-browser)/./node_modules/next/dist/compiled/scheduler/cjs/scheduler.development.js:261:34)
    at flushWork (webpack-internal:///(:5300/app-pages-browser)/./node_modules/next/dist/compiled/scheduler/cjs/scheduler.development.js:230:14)
    at MessagePort.performWorkUntilDeadline (webpack-internal:///(:5300/app-pages-browser)/./node_modules/next/dist/compiled/scheduler/cjs/scheduler.development.js:534:21)
```

**Comment by jtw-r** [comment] 2023-09-29 22:47
+1. Please re-open this issue

**Comment by Lazercat** [comment] 2023-09-30 05:16
+2, this is still happening

**Comment by glenyRodriguezSM** [comment] 2024-05-20 04:14
+3, this is still happening

**Comment by sharadregoti** [comment] 2024-06-01 03:06
Was anyone able to resolve this issue?

**Comment by optonpo** [comment] 2024-07-03 18:11
> Looks like this is not an issue with the SDK. I'll close this issue, @exipnus please let me know if you'd prefer to reopen.

@Widcket It seems that auth0/react users are having similar issue with Auth0Provider. If not the SDK, any suggestions beyond 'seems like'? At first glance, there are 50+ unanswered interactions since the issue was closed.

**Comment by Jelenbl** [comment] 2024-07-10 00:04
same issue - 


app/layout.js

```javascript
import { UserProvider } from '@auth0/nextjs-auth0/client';
import { AntdRegistry } from '@ant-design/nextjs-registry';

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function App({ children }) {
  return (

    <html lang="en">
      <UserProvider>
      <body>
          <AntdRegistry>
            {children}
          </AntdRegistry>
      </body>
      </UserProvider>
    </html>
  );
}

```

**Comment by JacksonMcKay** [comment] 2025-05-05 08:30
Sorry for commenting on an old issue but in my case I found that the Redux DevTools extension was causing my errors - both locally and in production. Not sure what the actual cause is but at least disabling the extension is a workaround if you're in the same boat as me :)

<img width="584" alt="Image" src="https://github.com/user-attachments/assets/3bd35774-d65c-4fe7-9b90-a0b6683e3905" />
