### ISSUE TITLE
Chunked or unchunked cookies not getting cleaned up

### ISSUE THREAD

**Issue by blazzy** [auth0/nextjs-auth0#465] opened 2021-08-17 15:51 UTC
### Describe the problem

The logic to clean up the cookies when switching between chunked and not chunked or vice versa seems to have issues. Our users are left with appSession cookies along with appSession.0 and appSession.1 cookies. This leads to cookie sizes around 8k or so.

### What was the expected behavior?

We expected users to have either the appSession or the appSession.0 and appSession.1 cookies. 

### Reproduction

I suspect this issue appears during the refresh token phase. Unfortunately don't have clear specific steps to reproduce.

Our solution is going to be to just shrink the size of the cookies so our users never get into a chunking cookie situation. Though that has proven more challenging than expected: https://github.com/auth0/nextjs-auth0/issues/416

### Environment

- nextjs-auth0 v1.50
- next v10.2.0

**Comment by blazzy** [comment] 2021-08-18 05:47
I found that we had three or different async functions invoking `getAccessToken`. I have a feeling this could have been a contributing factor. If all three were attempting to set and clear cookies for a newly refreshed tokens may they could have ended up setting up both a chunked and un-chunked version of the cookie?

**Comment by adamjmcgrath** [comment] 2021-08-23 12:35
Hi @blazzy - thanks for raising this

We have logic that should clean up chunked cookies if switching between chunked/unchunked and visa-versa https://github.com/auth0/nextjs-auth0/blob/main/tests/auth0-session/cookie-store.test.ts#L151-L180

And I'm not able to reproduce the issue with the `kitchen-sink` app. 

Adding the following handlers:

```js
// api/add.js
import { withApiAuthRequired, getSession } from '@auth0/nextjs-auth0';

export default withApiAuthRequired(async function shows(req, res) {
  const session = await getSession(req, res);
  session.foo = Array(5 * 1000)
    .fill('x')
    .join('');
  res.json({});
});

// api/remove.js
import { withApiAuthRequired, getSession } from '@auth0/nextjs-auth0';

export default withApiAuthRequired(async function shows(req, res) {
  const session = await getSession(req, res);
  delete session.foo;
  res.json({});
});
```

Then toggling between `/api/add` and `/api/remove` - I see the chunked and unchunked cookies being cleaned up as expected.

Are you able to repro this on localhost? Could you create a demo app?

**Comment by adamjmcgrath** [comment] 2021-08-23 12:37
> If all three were attempting to set and clear cookies for a newly refreshed tokens maybe they could have ended up setting up both a chunked and un-chunked version of the cookie?

It doesn't matter how many time you call `getAccessToken`, the cookies will be set/cleared up just once at the end of the request

**Comment by Widcket** [comment] 2021-08-30 15:16
@blazzy will close this issue, as it seems you've solved the problem. Please ping if you'd like to reopen.

**Closed by Widcket** 2021-08-30 15:16 UTC
Labels: needs investigation

**Comment by jasonmit** [comment] 2022-10-07 20:52
I'm see something very similar that was introduced after 1.7.0.

Our session cookie is being written in the response with `set-cookie` about five times - and it's quite large so the issue seems concerning.  I haven't isolated it further other than knowing this started occurring after upgrading from 1.7.0 to 1.9.0.

We also create our own instance of the client and I've already checked to ensure we're not mixing up multiple instances (as mentioned in the Docs).

**Comment by jason-yolabs** [comment] 2022-10-07 20:55
To better explain what I'm seeing, here's a screenshot:

<img width="1710" alt="image" src="https://user-images.githubusercontent.com/76751392/194651000-85715123-b28c-4ca8-b9c7-1df58e818026.png">

**Comment by jasonmit** [comment] 2022-10-10 18:51
@adamjmcgrath issue still present in `1.9.2`, first appears in `1.9.0`.   `1.8.0` appears to be the latest version w/o the bug.

I'll try and create pretty reproduction steps, we're not doing anything unconventional.  I also verified we were referencing multiple `auth0` clients as the docs allude to this happening when referencing multiple clients.

**Comment by adamjmcgrath** [comment] 2022-10-11 11:39
@jasonmit - my best guess is that you might be creating multiple instances of the SDK in a single request eg

```js
import { initAuth0 } from '@auth0/nextjs-auth0';

export default initAuth0().withApiAuthRequired(function myHandler(req, res) {
  const session = initAuth0().getSession(req, res);
  const accessToken = await (initAuth0().getAccessToken(req, res));
});
```

Rather than:


```js
import { initAuth0 } from '@auth0/nextjs-auth0';

const instance = initAuth0();

export default instance.withApiAuthRequired(function myHandler(req, res) {
  const session = instance.getSession(req, res);
  const accessToken = await instance.getAccessToken(req, res);
});
```
