### ISSUE TITLE
withMiddlewareAuthRequired on Next.js 13 throws 'req.cookies.keys is not a function'

### ISSUE THREAD

**Issue by wjrogers** [auth0/nextjs-auth0#892] opened 2022-11-01 15:18 UTC
### Checklist

- [X] The issue can be reproduced in the [sample app](https://github.com/auth0-samples/auth0-nextjs-samples/tree/main/Sample-01) (or N/A).
- [X] I have looked into the [README](https://github.com/auth0/nextjs-auth0#readme) and have not found a suitable solution or answer.
- [X] I have looked into the [examples](https://github.com/auth0/nextjs-auth0/blob/main/EXAMPLES.md) and have not found a suitable solution or answer.
- [X] I have looked into the [API documentation](https://auth0.github.io/nextjs-auth0/) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/nextjs-auth0/issues) and have not found a suitable solution or answer.
- [X] I have searched the [Auth0 Community](https://community.auth0.com/c/sdks/5) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Description

I am experimenting with the v2 beta on Next.js 13. I added middleware to my project following the examples in #815, and the server raises an error trying to read the request cookies:
```
at MiddlewareCookies.getAll (webpack-internal:///(middleware)/./node_modules/@auth0/nextjs-auth0/dist/utils/middleware-cookies.js:18:39)
    at CookieStore.eval (webpack-internal:///(middleware)/./node_modules/@auth0/nextjs-auth0/dist/auth0-session/cookie-store.js:128:54)
    at step (webpack-internal:///(middleware)/./node_modules/tslib/tslib.es6.js:130:23)
    at Object.eval [as next] (webpack-internal:///(middleware)/./node_modules/tslib/tslib.es6.js:111:53)
    at eval (webpack-internal:///(middleware)/./node_modules/tslib/tslib.es6.js:104:71)
    at new Promise (<anonymous>)
    at Module.__awaiter (webpack-internal:///(middleware)/./node_modules/tslib/tslib.es6.js:100:12)
    at CookieStore.read (webpack-internal:///(middleware)/./node_modules/@auth0/nextjs-auth0/dist/auth0-session/cookie-store.js:122:24)
    at SessionCache.eval (webpack-internal:///(middleware)/./node_modules/@auth0/nextjs-auth0/dist/session/cache.js:20:63)
```

I understand this is all very new. Thanks for your work on implementing middleware support!

### Reproduction

1. Configure Auth0 (e.g. using the sample app)
2. Install `next@13.0.1`
3. Add a `middleware.ts` to the project:
    ```ts
    import { withMiddlewareAuthRequired } from "@auth0/nextjs-auth0/middleware";

    export default withMiddlewareAuthRequired();
    ````
4. Run the server and load a page in the browser

### SDK version

2.0.0-beta.1

### Next.js version

13.0.1

### Node.js version

16.18.0

**Comment by adamjmcgrath** [comment] 2022-11-02 10:23
Thanks for raising @wjrogers 

This looks like it's caused by a breaking change in next@13.0.1 from https://github.com/vercel/next.js/pull/41526

You should be able to use next@13.0.0 while we investigate

**Comment by adamjmcgrath** [comment] 2022-11-02 17:49
This is fixed in https://github.com/auth0/nextjs-auth0/releases/tag/v2.0.0-beta.2

**Closed by adamjmcgrath** 2022-11-02 17:49 UTC
Labels: needs investigation
