### ISSUE TITLE
invalid_grant (Invalid authorisation code) error using basic-example with nextjs dynamic routes in chrome

### ISSUE THREAD

**Issue by YelloJW** [auth0/nextjs-auth0#170] opened 2020-09-22 09:02 UTC
### Description

- We have closely followed the basic example from your repo here https://github.com/auth0/nextjs-auth0/tree/master/examples/basic-example, with a slight adjustment to our withAuth wrapper and api/login route for redirecting users. 
- In our withAuth wrapper we check if a user has a valid session by calling the api/me endpoint and if they don’t we call a function which redirects the user to api/login, providing a redirect path from context if one exists (see code extracts below)
- When users are redirected, specifically to dynamic paths e.g. book/[book_id], we often see an error `invalid_grant (Invalid authorisation code)` from api/callback (screenshot 1) - note api/callback is unchanged from your example. We see this error in a local and hosted environment and only in chrome (not reproducible in Safari or Firefox). It can be resolved by selecting `Disable cache` from the Network tab in chrome dev tools (screenshot 2), but this is obviously not a viable solution for our users. This suggests there is an interaction between nextjs-auth0, nextjs dynamic routing and chrome that is causing the error.
- Code snippets from withAuth and api/login are provided below for visibility. Any help or suggestions as to how to resolve this issue would be greatly appreciated. 

### Screenshots 
1.
![image](https://user-images.githubusercontent.com/52374284/93860418-fdc4c500-fcb6-11ea-99ac-a5cb27730d75.png)
2.
![image](https://user-images.githubusercontent.com/52374284/93862482-08cd2480-fcba-11ea-899b-7d8a4cee5d82.png)

### Code extracts
// withAuth.tsx
```
const redirectPath = '/api/login'

const redirect = (context: NextPageContext): void => {
  if (context?.res != null) {
    context.res.writeHead(301, { Location: `${redirectPath}?redirect=${context.asPath}` })
    context.res.end()
  } else {
    document.location.pathname = redirectPath
  }
}

export default function withAuth<P extends object>(InnerComponent: NextPage<P> | NextComponentType<P>) {
  return class Authenticated extends Component<P> {
    static async getInitialProps(context: NextPageContext & P): Promise<object> {
      try {
        const { status, data } = await nextApi<User>('/api/me', context)
        if (status !== OK || data == null) {
          redirect(context)
        }
      } catch (error) {
        console.error(error)
        redirect(context)
      }
      let componentProps = {}
      if (InnerComponent.getInitialProps) {
        componentProps = InnerComponent.getInitialProps(context)
      }
      return componentProps
    }

    constructor(props: P) {
      super(props)
    }

    render(): JSX.Element {
      return <div>{<InnerComponent {...this.props} />}</div>
    }
  }
}
```

// api/login.ts
```
export default async function login(req: NextApiRequest, res: NextApiResponse): Promise<void> {
  try {
    const redirectTo = (req.query.redirect as string) || '/'
    await auth0?.handleLogin(req, res, { redirectTo })
  } catch (error) {
    console.error(error)
    res.status(error.status || 500).end(error.message)
  }
}
```

### Environment

@auth0/nextjs-auth0: 0.16.0
next: 9.5.2

**Comment by sioquim** [comment] 2020-12-14 21:47
@YelloJW did you manage to find a workaround? Getting a similar issue at the moment.

**Comment by YelloJW** [comment] 2021-01-06 11:21
> @YelloJW did you manage to find a workaround? Getting a similar issue at the moment.

No not yet @sioquim

**Comment by Widcket** [comment] 2021-01-16 01:39
Can you please check if this still happens with the 1.0.0 beta? We completely reworked the session logic, so this might no longer be the case.

**Comment by adamjmcgrath** [comment] 2021-01-27 15:53
> context.res.writeHead(301, { Location: `${redirectPath}?redirect=${context.asPath}` })

Hi @YelloJW - thanks for sharing your code snippet. I noticed that you're using a `301 Permanent Redirect` to redirect your user to the login page.

This should be a temporary redirect `302`, otherwise subsequent requests to the protected page will be redirected to login from the disk cache before the server can respond to them. This probably explains why "It can be resolved by selecting Disable cache from the Network tab".

I can't reproduce the `invalid_grant (Invalid authorisation code)` error with the code you've shared though - can you try replacing the `301` with a `302` and seeing if it fixes it.

If you are still having problems, can you share your config and any steps you think might help me reproduce it - or the whole app if you can.

**Comment by TommySorensen** [comment] 2021-01-28 13:11
@adamjmcgrath You could also use a `307`

![image](https://user-images.githubusercontent.com/4134473/106143064-904c0800-6172-11eb-9db1-7d75554d2553.png)

**Comment by adamjmcgrath** [comment] 2021-01-28 16:41
> @adamjmcgrath You could also use a 307

yep 👍

**Comment by adamjmcgrath** [comment] 2021-02-02 17:00
Hi @YelloJW - I'm going to close this since I think https://github.com/auth0/nextjs-auth0/issues/170#issuecomment-768381957 has answered your question.

If it hasn't, please ping me on this issue and I'll reopen this so we can investigate further.

**Closed by adamjmcgrath** 2021-02-02 17:00 UTC
Labels: needs investigation
