### ISSUE TITLE
Race condition updating a session when rolling session / auto-save enabled. 

### ISSUE THREAD

**Issue by dkokotov** [auth0/nextjs-auth0#1286] opened 2023-07-13 22:52 UTC
### Checklist

- [X] I have looked into the [Readme](https://github.com/auth0/nextjs-auth0#readme), [Examples](https://github.com/auth0/nextjs-auth0/blob/main/EXAMPLES.md), and [FAQ](https://github.com/auth0/nextjs-auth0/blob/main/FAQ.md) and have not found a suitable solution or answer.
- [X] I have looked into the [API documentation](https://auth0.github.io/nextjs-auth0/) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/nextjs-auth0/issues) and have not found a suitable solution or answer.
- [X] I have searched the [Auth0 Community](https://community.auth0.com) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Describe the problem you'd like to have solved

I was trying to use `updateSession` to store some data in the session (in an api route) and later retrieve it via `getSession` (in a different api route). The issue I ran into is that sometimes, the session returned from `getSession` in the subsequent api route would be missing the additional data added in the `updateSession` call.

The cause, I believe, is a race condition created by having rolling sessions, stateless sessions, and auto-save enabled (which are all defaults). What would happen is sometimes, before the request to the api route that calls `updateSession` returned, the client would make another unrelated xhr request (unrelated to the original request). that request would not yet have the updated `appSession` cookie. and because rolling sessions/auto-save is enabled, when this new request completed (which would be after the request that updated the session), it would have `Set-Cookie` headers that overwrote the updated session.

### Describe the ideal solution

I don't have an ideal solution in mind - I've thought of some workarounds which I list in the section below. I am mostly raising the issue because this seems like a fundamental problem with updating a session when using the library with default settings (stateless session, rolling session enabled, auto save enabled). Basically it seems very likely people will run into this and at the very least I would suggest pointing this out in the documentation for `updateSession` API and/or settings around rolling session / auto-save. 

Secondarily, maybe there is a better workaround or something I haven't thought of.

### Alternatives and current workarounds

I confirmed that disabling auto-save eliminates the issue. so one workaround is to disable auto-save and only save the session on specific interactions that are unlikely to cause race conditions (eg on route changes). Or of course one could give up on rolling sessions altogether.

Another workaround I thought of is to switch to stateful sessions. I think there *is* still a potential race condition with stateful sessions because the update session could happen between a read and write to the store of a route that is doing an auto-save - but it would be much less likely since the "window" between the read and write is much shorter in this scenario. 

### Additional context

I saw there were previous somewhat related issues filed:  https://github.com/auth0/nextjs-auth0/issues/907 and https://github.com/auth0/nextjs-auth0/issues/544

I think those issues were closed out as "working as expected". And I guess you could say in a sense it is. But I feel like these downsides of the default settings (stateless/rolling/auto-saved sessions) are fairly significant - basically its nearly impossible to ensure reliable updating of session due to the race conditions - and are not obvious ahead of time. Thus users should at least be warned via docs. I would even argue that the default settings should be different, but that would be of course a breaking change and thus likely a non-starter.

**Comment by adamjmcgrath** [comment] 2023-07-18 11:55
@dkokotov - thanks for raising this.

As discussed in https://github.com/auth0/nextjs-auth0/issues/907 and https://github.com/auth0/nextjs-auth0/issues/544 this is the tradeoff of having a stateless session and we have an array of features to mitigate this.

The default for this library should be easy to use without additional infrastructure, that stateful sessions require - so we don't plan to change the default. Happy to consider a change to the docs if you would like to propose one in a PR.

Closing as duplicate of https://github.com/auth0/nextjs-auth0/issues/907 and https://github.com/auth0/nextjs-auth0/issues/544

**Closed by adamjmcgrath** 2023-07-18 11:55 UTC
