### ISSUE TITLE
Testing SDK with sinon

### ISSUE THREAD

**Issue by mustafaKamal-fe** [auth0/nextjs-auth0#330] opened 2021-03-07 02:36 UTC
### Description

>I was trying to test the SDK instance of my app with `sinon` library stubs and spies. I was trying to make sure a middleware 
   that retrievs user `app_metadata` and then do some logic on them is working as expected. 

### Reproduction

             `it('should through if roles do not match', async function () {
		
		// stub getUser
		const stubGetUser = sinon.stub(Auth0ManagementAPI, 'getUser');
		stubGetUser.resolves({ app_metadata: { roles: ['this role'] } });

		// stub getSession
		const stubGetSession = sinon.stub(auth0, 'getSession');
		stubGetSession.returns({ user: { sub: 'somerandomsub' } });

		// stub checkUserRole
		const stubCheckUserRole = sinon.stub({ chekUserRole }, 'chekUserRole');

		// fake HTTP req,res objects
		const req: any = {};
		const res: any = {};

		await stubCheckUserRole(req, res, 'is not like this role');

		expect(stubCheckUserRole).to.throw();
	});`

`UnhandledPromiseRejectionWarning: TypeError: "secret" is required
    at Object.get (/home/gistcodee/dev/swagy/node_modules/@auth0/nextjs-auth0/src/auth0-session/get-config.ts:158:11)
    at Object.getConfig (/home/gistcodee/dev/swagy/node_modules/@auth0/nextjs-auth0/src/config.ts:431:22)
    at initAuth0 (/home/gistcodee/dev/swagy/node_modules/@auth0/nextjs-auth0/src/index.ts:64:38)
    at Object.<anonymous> (/home/gistcodee/dev/swagy/lib/backend/auth/nextAuht0.ts:14:16)
    at Module._compile (internal/modules/cjs/loader.js:1015:30)
    at Module._compile (/home/gistcodee/dev/swagy/node_modules/pirates/lib/index.js:99:24)
    at Module.m._compile (/home/gistcodee/dev/swagy/node_modules/ts-node/src/index.ts:1056:23)
    at Module._extensions..js (internal/modules/cjs/loader.js:1035:10)
    at require.extensions.<computed> (/home/gistcodee/dev/swagy/node_modules/ts-node/src/index.ts:1059:12)
    at Object.newLoader [as .ts] (/home/gistcodee/dev/swagy/node_modules/pirates/lib/index.js:104:7)
    at Module.load (internal/modules/cjs/loader.js:879:32)
    at Function.Module._load (internal/modules/cjs/loader.js:724:14)
    at Module.require (internal/modules/cjs/loader.js:903:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/home/gistcodee/dev/swagy/test/try.spec.ts:5:1)
    at Module._compile (internal/modules/cjs/loader.js:1015:30)
    at Module._compile (/home/gistcodee/dev/swagy/node_modules/pirates/lib/index.js:99:24)
    at Module.m._compile (/home/gistcodee/dev/swagy/node_modules/ts-node/src/index.ts:1056:23)
    at Module._extensions..js (internal/modules/cjs/loader.js:1035:10)
    at require.extensions.<computed> (/home/gistcodee/dev/swagy/node_modules/ts-node/src/index.ts:1059:12)
    at Object.newLoader [as .ts] (/home/gistcodee/dev/swagy/node_modules/pirates/lib/index.js:104:7)
    at Module.load (internal/modules/cjs/loader.js:879:32)
    at Function.Module._load (internal/modules/cjs/loader.js:724:14)
    at Module.require (internal/modules/cjs/loader.js:903:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at /home/gistcodee/dev/swagy/node_modules/mocha/lib/mocha.js:427:36
    at Array.forEach (<anonymous>)
    at Mocha.loadFiles (/home/gistcodee/dev/swagy/node_modules/mocha/lib/mocha.js:424:14)
    at Mocha.run (/home/gistcodee/dev/swagy/node_modules/mocha/lib/mocha.js:1003:10)
    at run (/home/gistcodee/dev/swagy/node_modules/mocha/lib/cli/watch-run.js:265:20)
    at rerun (/home/gistcodee/dev/swagy/node_modules/mocha/lib/cli/watch-run.js:293:5)
    at Object.scheduleRun (/home/gistcodee/dev/swagy/node_modules/mocha/lib/cli/watch-run.js:286:7)
    at FSWatcher.<anonymous> (/home/gistcodee/dev/swagy/node_modules/mocha/lib/cli/watch-run.js:188:14)
    at FSWatcher.emit (events.js:314:20)
    at FSWatcher.EventEmitter.emit (domain.js:483:12)
    at FSWatcher.emitWithAll (/home/gistcodee/dev/swagy/node_modules/chokidar/index.js:535:32)
    at FSWatcher._emit (/home/gistcodee/dev/swagy/node_modules/chokidar/index.js:626:8)
    at listener (/home/gistcodee/dev/swagy/node_modules/chokidar/lib/nodefs-handler.js:370:20)
(node:27222) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)`
### Environment

> Please provide the following:

- **Version of this library used:** latest
- **Version of the platform or framework used, if applicable:** nextjs
- **Other relevant versions (language, server software, OS, browser):**chrome
- **Other modules/plugins/libraries that might be involved:**`sinon`

**Comment by adamjmcgrath** [comment] 2021-03-08 12:45
duplicate of #331

**Closed by adamjmcgrath** 2021-03-08 12:45 UTC
