### ISSUE TITLE
handleCallback - Cannot read property 'toString' of undefined error

### ISSUE THREAD

**Issue by jaredgalanis** [auth0/nextjs-auth0#396] opened 2021-05-11 00:43 UTC
Visits to our tenant's domain that result in an unauthorized error with an error description of wrong email or verification code result in a redirect to our callback url that ends up producing the following unhandled error from within nextjs-auth0 of `Cannot read property 'toString' of undefined`.

The callback url that produces this error is:`https://{auth0-domain-here}/api/auth/callback#error=unauthorized&error_description=Wrong email or verification code`

related to: https://github.com/auth0/nextjs-auth0/issues/371, but the solution there is not the issue as the new `api/auth` routes are being used.

I'd expect these kinds of things to be more gracefully handled with perhaps a redirect to `api/auth/logout`.

We are using passwordless authentication with magic link and we are on `v1.3.0`.

**Comment by jaredgalanis** [comment] 2021-05-11 13:57
Thanks @adamjmcgrath! 

We are using the universal login page and initiating the login from the application in these cases. I don't think we were using `response_mode: query` though. Is that a parameter I need to explicitly pass somewhere? When initializing the client maybe?

**Comment by adamjmcgrath** [comment] 2021-05-11 15:33
Hi @jaredgalanis - you shouldn't need to change anything, it's the default for `response_type: 'code'` which is the default for this SDK.

If you're initating the login from the SDK then I'm not sure why you're getting the `fragment` response back from the Universal Login Page. Do you have a running version of your app I can look at?

**Comment by adamjmcgrath** [comment] 2021-05-11 15:34
@jaredgalanis - do successful logins come back with the `code` and `state` on the fragment or is it just errors?

**Comment by jaredgalanis** [comment] 2021-05-11 17:13
> @jaredgalanis - do successful logins come back with the `code` and `state` on the fragment or is it just errors?

Yes they do.

**Comment by adamjmcgrath** [comment] 2021-05-12 12:32
Hi @jaredgalanis - I can't explain why your error is coming back in the fragment when you're initiating loigin from the app with the defaults authorization params and I can't reproduce the issue myself.

It sounds like an issue with your tenant configuration rather than this SDK

**Comment by jaredgalanis** [comment] 2021-05-14 17:27
> Hi @jaredgalanis - I can't explain why your error is coming back in the fragment when you're initiating loigin from the app with the default authorization params and I can't reproduce the issue myself.
> 
> It sounds like an issue with your tenant configuration rather than this SDK.
> 
> Can you share the full `/authorize` url from your browser network logs of a login that ends with a callback with the `error` and `error_description` in the fragment?

@adamjmcgrath does this give you what you need?

`https://{ourdomain}/api/auth/callback#error=unauthorized&error_description=Wrong%20email%20or%20verification%20code.&state=hKFo2SA2WXF0anhJX0ZMck10aDhRSUhtRUoycmRpc1A3SExzRKFupWxvZ2luo3RpZNkgZjR1dXNsTlhnT2hLTksyMnM2ZklRVEdfTU5XNGJkdl-jY2lk2SBEZDBsVGd2VE9ESTNJSWpLajVjNzBTR2pDZnFWQXJNTg`

**Comment by jaredgalanis** [comment] 2021-05-14 17:35
> Hi @jaredgalanis - I can't explain why your error is coming back in the fragment when you're initiating loigin from the app with the default authorization params and I can't reproduce the issue myself.
> 
> It sounds like an issue with your tenant configuration rather than this SDK.
> 
> Can you share the full `/authorize` url from your browser network logs of a login that ends with a callback with the `error` and `error_description` in the fragment?

@adamjmcgrath, it actually looks like authorize isn't even hit. Attaching a HAR file of the requests for you to look at.


[visit-workplace-dev.givinga.com.har.zip](https://github.com/auth0/nextjs-auth0/files/6480328/visit-workplace-dev.givinga.com.har.zip)

**Comment by jaredgalanis** [comment] 2021-05-14 23:02
> > Hi @jaredgalanis - I can't explain why your error is coming back in the fragment when you're initiating loigin from the app with the default authorization params and I can't reproduce the issue myself.
> > It sounds like an issue with your tenant configuration rather than this SDK.
> > Can you share the full `/authorize` url from your browser network logs of a login that ends with a callback with the `error` and `error_description` in the fragment?
> 
> @adamjmcgrath, it actually looks like authorize isn't even hit. Attaching a HAR file of the requests for you to look at.
> 
> [visit-workplace-dev.givinga.com.har.zip](https://github.com/auth0/nextjs-auth0/files/6480328/visit-workplace-dev.givinga.com.har.zip)

Actually here's the authorize that happens when we let the login handler redirect someone to the universal login page from the application:

```
https://visit-workplace-dev.us.auth0.com/authorize?client_id=Dd0lTgvTODI3IIjKj5c70SGjCfqVArMN&scope=openid%20profile%20email&response_type=code&redirect_uri=https%3A%2F%2Fvisit-workplace-dev.givinga.com%2Fapi%2Fauth%2Fcallback&audience=https%3A%2F%2Fdev-api-gateway.givinga.com&email=jared%2Byahooz4%40pacifica.codes&first_name=jared&last_name=galantis&street_address=921%20W%2038th%20St&city=Baltimore&state_province=MD&country=US&zip_code=21211&auth_token=38ae3940e4f7e990495081a3f0936260098a6e0da451379b7720ad970355b620&nonce=tdcKOQ8ErDOMMnk8y3Vd5vjLian6faGHFWYq39ZQkv0&state=eyJyZXR1cm5UbyI6Imh0dHBzOi8vdmlzaXQtd29ya3BsYWNlLWRldi5naXZpbmdhLmNvbSJ9&code_challenge=UNZrCejU1rveTSxOcNxSop38jCYc4l8MFnB1TayEot0&code_challenge_method=S256
```

**Comment by adamjmcgrath** [comment] 2021-05-17 14:39
Hi @jaredgalanis 

> `https://visit-workplace-dev.us.auth0.com/authorize?client_id=Dd0lTgvTODI3IIjKj5...`

When I visit your authorization link and follow the link it sends out as an email, I get returned to a callback error page with the `error` and `error_description` sent in the query (not the fragment) - which is what I would expect for `response_type=code`, eg
https://visit-workplace-dev.givinga.com/api/auth/callback?error=unauthorized&error_description=Wrong%20email%20or%20verification%20code.&state=eyJyZXR1cm5UbyI6Imh0dHBzOi8vdmlzaXQtd29ya3BsYWNlLWRldi5naXZpbmdhLmNvbSJ9

**Comment by jaredgalanis** [comment] 2021-05-17 14:59
> Hi @jaredgalanis
> 
> > `https://visit-workplace-dev.us.auth0.com/authorize?client_id=Dd0lTgvTODI3IIjKj5...`
> 
> When I visit your authorization link and follow the link it sends out as an email, I get returned to a callback error page with the `error` and `error_description` sent in the query (not the fragment) - which is what I would expect for `response_type=code`, eg
> https://visit-workplace-dev.givinga.com/api/auth/callback?error=unauthorized&error_description=Wrong%20email%20or%20verification%20code.&state=eyJyZXR1cm5UbyI6Imh0dHBzOi8vdmlzaXQtd29ya3BsYWNlLWRldi5naXZpbmdhLmNvbSJ9

Hey @adamjmcgrath, yes I get the same response when visiting that authorize end point directly, but in our flow the issue occurs when you attempt to use a magic link more than once. When I click a magic link, which is linked here https://visit-workplace-dev.us.auth0.com/passwordless/verify_redirect, it redirects to https://visit-workplace-dev.us.auth0.com/login/callback which redirects to https://visit-workplace-dev.givinga.com/api/auth/callback without query params and with the fragment. 

If you take a look at the HAR file I first linked to above it should provide you with the full detail on those network interactions.

**Comment by adamjmcgrath** [comment] 2021-05-19 09:53
Hi @jaredgalanis - this is getting out of the scope of this SDK

But, you could try setting `{ "response_type": "code" }` in "Email > Authentication Parameters" in https://manage.auth0.com/#connections/passwordless
![image](https://user-images.githubusercontent.com/1299658/118792650-c4694700-b88f-11eb-80f0-f8ef27e98187.png)

The `response_type` QP should be `code` (not `token`) in your `https://visit-workplace-dev.us.auth0.com/passwordless/verify_redirect?scope=openid%20profile&response_type=token&...` url

**Comment by adamjmcgrath** [comment] 2021-05-25 09:40
@jaredgalanis - closing this, feel free to ping me if you'd like me to reopen

**Closed by adamjmcgrath** 2021-05-25 09:40 UTC
Labels: question

**Comment by jaredgalanis** [comment] 2021-05-27 15:32
> @jaredgalanis - closing this, feel free to ping me if you'd like me to reopen

Hey @adamjmcgrath, sorry for the delay, I was traveling last week.

This config change required me to add this auth param to the place where I create the magic link via the api. That seems to work, but when I try to recreate the problem I am now getting a query param instead of a fragment but I'm getting a different error out of the SDK.

`https://visit-workplace-dev.givinga.com/api/auth/callback?error=unauthorized&error_description=Wrong%20email%20or%20verification%20code.&state=hKFo2SBZOUpSUy0wNnVDTWprOTROTERiYlRmcGNLTnlXdjlmS6FupWxvZ2luo3RpZNkgdllfMGt2LTRFWVBldHN3OHlCaFRxRFE2eExLSFZPWDajY2lk2SBEZDBsVGd2VE9ESTNJSWpLajVjNzBTR2pDZnFWQXJNTg`

Gives me this error:

`checks.state argument is missing`

**Comment by jaredgalanis** [comment] 2021-05-27 16:06
I suppose I can try to handle this error in a custom way on our end or check if there is an active session and redirect to the app if so.

**Comment by adamjmcgrath** [comment] 2021-05-27 16:40
> I suppose I can try to handle this error in a custom way on our end or check if there is an active session and redirect to the app if so.

Yep `checks.state argument is missing` is the correct error in this scenario, since you're visiting the callback page without any state cookies to check (they were removed in your previous successful login)

**Comment by FDiskas** [comment] 2021-09-13 17:31
Don't know why I'm getting `checks.state argument is missing` - I also tryied to add my own cookie - still the same
![Screenshot from 2021-09-13 19-50-18](https://user-images.githubusercontent.com/468006/133129734-263ca33d-c310-4bab-b778-c53176325b2b.png)

**Comment by osdiab** [comment] 2021-09-21 12:39
I'm not sure if this is related but I'm also seeing this `Cannot read property 'toString' of undefined` error for a client of mine who's trying to log in through an Okta Portal via SAML to our application (we use universal login) - might this be related?

**Comment by seanlindo** [comment] 2021-11-10 23:17
@osdiab I'm getting this exact same error under the exact same circumstances. Were you able to find a solution?

**Comment by seanlindo** [comment] 2021-11-11 14:44
@osdiab That's pretty helpful, thank you! I'll try something similar.
