### ISSUE TITLE
Bug because change in oidc-token-hash version check

### ISSUE THREAD

**Issue by dkleber89** [auth0/nextjs-auth0#1154] opened 2023-04-11 14:26 UTC
### Checklist

- [X] The issue can be reproduced in the [sample app](https://github.com/auth0-samples/auth0-nextjs-samples/tree/main/Sample-01) (or N/A).
- [X] I have looked into the [README](https://github.com/auth0/nextjs-auth0#readme) and have not found a suitable solution or answer.
- [X] I have looked into the [examples](https://github.com/auth0/nextjs-auth0/blob/main/EXAMPLES.md) and have not found a suitable solution or answer.
- [X] I have looked into the [API documentation](https://auth0.github.io/nextjs-auth0/) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/nextjs-auth0/issues) and have not found a suitable solution or answer.
- [X] I have searched the [Auth0 Community](https://community.auth0.com/c/sdks/5) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Description

Before 3 days this (https://github.com/panva/oidc-token-hash/commit/ba8b2e73a58c872865008158fd5cb3afd276b0b2) change comes into the oidc-token-hash dependency -> this is a dependency of openid-client and this is a dependency of the @auth0/nextjs-auth0 library -> And because of semver and a patch change in the underlaying lib on a install its updated immediately

This causes the following error: 
![image](https://user-images.githubusercontent.com/31743141/231186085-2f627ff1-fa03-45c9-9f2d-7f6d84539ceb.png)

After a manual downgrade of the dependency to 5.0.1 it working fine as before

### Reproduction

1. Use latest SDK
2. npm update so u have the newest sub dependencies
3. you have a error
4. manually downgrade oidc-token-hash to 5.0.1 (One patch version back)
5. you have no error

I not exactly now what happening because on node.js also the new way would work without problem but in context of nextjs and the auth lib its not working ... is there someting that calls it on client side?

### SDK version

2.4.0

### Next.js version

12.3.4

### Node.js version

v18.14.0

**Comment by adamjmcgrath** [comment] 2023-04-11 15:00
Hi @dkleber89 - thanks for raising this

I've just updated the [example app](https://github.com/auth0/nextjs-auth0/tree/main/examples/kitchen-sink-example) to use `oidc-token-hash@5.0.2` and can't reproduce the issue you're seeing.

The `openid-client` (and its dependency `oidc-token-hash`) library is imported by `@auth0/nextjs-auth0` and should only be used in the Node runtime.

Could you be importing it into the browser runtime somehow perhaps?

**Comment by adamjmcgrath** [comment] 2023-04-12 09:53
AFAIK `process.versions.node` is available in the Node runtime (see https://nodejs.org/docs/latest-v12.x/api/process.html#process_process_versions) so as long as you're importing it into the Node runtime it should work.

If anyone can provide an example repo that demonstrates the issue I'd be happy to debug it.

**Comment by AliArdaOrhan** [comment] 2023-04-17 15:35
I had this issue as well and fixed with @MilanLund suggestions. It's very annoying bug as it doesn't manifests itself in codebase.

**Comment by QianKuang-nyu** [comment] 2023-04-19 06:10
I solved this problem by following another instruction. Repost here if someone can get help from this.

https://github.com/auth0/nextjs-auth0/issues/1139#issuecomment-1498664260

**Comment by adamjmcgrath** [comment] 2023-04-19 09:56
Thanks for sharing @QianKuang-nyu 

This is what I suspect is the issue - the node code in the library is being run on the browser (because you're using `getInitialProps`, importing `withPageAuthRequired` from the [server exports](https://github.com/auth0/nextjs-auth0#server-for-nodejs) instead of the [client exports](https://github.com/auth0/nextjs-auth0#client-for-the-browser), or something similar)

> It's very annoying bug as it doesn't manifests itself in codebase.

I appreciate this is difficult to debug, but this error happens at import time, so it's difficult to run some code before this to raise a better error.

Am closing, as I believe the issue can be resolved with https://github.com/auth0/nextjs-auth0/issues/1139#issuecomment-1498664260 - if you think there's an issue in the SDK and can provide a reproducible case, I'd be happy to investigate

**Closed by adamjmcgrath** 2023-04-19 09:56 UTC
Labels: question
